//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AccountStatus.
const (
	Active AccountStatus = "active"
	Closed AccountStatus = "closed"
	Hidden AccountStatus = "hidden"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	case Hidden:
		return true
	default:
		return false
	}
}

// Defines values for AccountType.
const (
	Checking   AccountType = "checking"
	CreditCard AccountType = "credit_card"
	Investment AccountType = "investment"
	Loan       AccountType = "loan"
	OtherAsset AccountType = "other_asset"
	OtherDebt  AccountType = "other_debt"
	RealEstate AccountType = "real_estate"
	Savings    AccountType = "savings"
	Vehicle    AccountType = "vehicle"
)

// Valid indicates whether the value is a known member of the AccountType enum.
func (e AccountType) Valid() bool {
	switch e {
	case Checking:
		return true
	case CreditCard:
		return true
	case Investment:
		return true
	case Loan:
		return true
	case OtherAsset:
		return true
	case OtherDebt:
		return true
	case RealEstate:
		return true
	case Savings:
		return true
	case Vehicle:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	ClosedAt    *time.Time     `json:"closed_at,omitempty"`
	CreatedAt   time.Time      `json:"created_at"`
	CreditLimit *float64       `json:"credit_limit,omitempty"`
	Id          int            `json:"id"`
	IsAsset     bool           `json:"is_asset"`
	Name        string         `json:"name"`
	Status      *AccountStatus `json:"status,omitempty"`
	Type        AccountType    `json:"type"`
}

// AccountBalance defines model for AccountBalance.
type AccountBalance struct {
	AsOfDate *time.Time  `json:"as_of_date,omitempty"`
	Balance  *float64    `json:"balance,omitempty"`
	Id       int         `json:"id"`
	Name     string      `json:"name"`
	Type     AccountType `json:"type"`
}

// AccountInput defines model for AccountInput.
type AccountInput struct {
	CreditLimit *float64       `json:"credit_limit,omitempty"`
	IsAsset     bool           `json:"is_asset"`
	Name        string         `json:"name"`
	Status      *AccountStatus `json:"status,omitempty"`
	Type        AccountType    `json:"type"`
}

// AccountSnapshot defines model for AccountSnapshot.
type AccountSnapshot struct {
	AccountId int       `json:"account_id"`
	AsOfDate  time.Time `json:"as_of_date"`
	Balance   float64   `json:"balance"`
	Id        int       `json:"id"`
}

// AccountSnapshotInput defines model for AccountSnapshotInput.
type AccountSnapshotInput struct {
	AsOfDate time.Time `json:"as_of_date"`
	Balance  float64   `json:"balance"`
}

// AccountStatus defines model for AccountStatus.
type AccountStatus string

// AccountType defines model for AccountType.
type AccountType string

// AccountTypeGroup defines model for AccountTypeGroup.
type AccountTypeGroup struct {
	Accounts []AccountBalance `json:"accounts"`
	Subtotal float64          `json:"subtotal"`
	Type     AccountType      `json:"type"`
}

// NetWorthSummary defines model for NetWorthSummary.
type NetWorthSummary struct {
	AssetGroups []AccountTypeGroup `json:"asset_groups"`
	DebtGroups  []AccountTypeGroup `json:"debt_groups"`
	NetWorth    float64            `json:"net_worth"`
	TotalAssets float64            `json:"total_assets"`
	TotalDebts  float64            `json:"total_debts"`
}

// NetWorthTrendPoint defines model for NetWorthTrendPoint.
type NetWorthTrendPoint struct {
	AsOfDate    time.Time `json:"as_of_date"`
	NetWorth    float64   `json:"net_worth"`
	TotalAssets float64   `json:"total_assets"`
	TotalDebts  float64   `json:"total_debts"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = AccountInput

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = AccountInput

// CreateAccountSnapshotJSONRequestBody defines body for CreateAccountSnapshot for application/json ContentType.
type CreateAccountSnapshotJSONRequestBody = AccountSnapshotInput

// UpdateAccountSnapshotJSONRequestBody defines body for UpdateAccountSnapshot for application/json ContentType.
type UpdateAccountSnapshotJSONRequestBody = AccountSnapshotInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request)

	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)

	// (DELETE /accounts/{id})
	DeleteAccount(w http.ResponseWriter, r *http.Request, id int)

	// (GET /accounts/{id})
	GetAccount(w http.ResponseWriter, r *http.Request, id int)

	// (PUT /accounts/{id})
	UpdateAccount(w http.ResponseWriter, r *http.Request, id int)

	// (GET /accounts/{id}/snapshots)
	ListAccountSnapshots(w http.ResponseWriter, r *http.Request, id int)

	// (POST /accounts/{id}/snapshots)
	CreateAccountSnapshot(w http.ResponseWriter, r *http.Request, id int)

	// (DELETE /accounts/{id}/snapshots/{snapshotId})
	DeleteAccountSnapshot(w http.ResponseWriter, r *http.Request, id int, snapshotId int)

	// (PUT /accounts/{id}/snapshots/{snapshotId})
	UpdateAccountSnapshot(w http.ResponseWriter, r *http.Request, id int, snapshotId int)

	// (GET /net-worth/summary)
	GetNetWorthSummary(w http.ResponseWriter, r *http.Request)

	// (GET /net-worth/trend)
	GetNetWorthTrend(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccount(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccountSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ListAccountSnapshots(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccountSnapshots(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccountSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateAccountSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccountSnapshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAccountSnapshot operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccountSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "snapshotId" -------------
	var snapshotId int

	err = runtime.BindStyledParameterWithOptions("simple", "snapshotId", r.PathValue("snapshotId"), &snapshotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "snapshotId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccountSnapshot(w, r, id, snapshotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccountSnapshot operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccountSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "snapshotId" -------------
	var snapshotId int

	err = runtime.BindStyledParameterWithOptions("simple", "snapshotId", r.PathValue("snapshotId"), &snapshotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "snapshotId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccountSnapshot(w, r, id, snapshotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNetWorthSummary operation middleware
func (siw *ServerInterfaceWrapper) GetNetWorthSummary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNetWorthSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNetWorthTrend operation middleware
func (siw *ServerInterfaceWrapper) GetNetWorthTrend(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNetWorthTrend(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts", wrapper.ListAccounts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/accounts", wrapper.CreateAccount)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/accounts/{id}", wrapper.DeleteAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{id}", wrapper.GetAccount)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/accounts/{id}", wrapper.UpdateAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{id}/snapshots", wrapper.ListAccountSnapshots)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/accounts/{id}/snapshots", wrapper.CreateAccountSnapshot)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/accounts/{id}/snapshots/{snapshotId}", wrapper.DeleteAccountSnapshot)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/accounts/{id}/snapshots/{snapshotId}", wrapper.UpdateAccountSnapshot)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/net-worth/summary", wrapper.GetNetWorthSummary)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/net-worth/trend", wrapper.GetNetWorthTrend)

	return m
}

type ListAccountsRequestObject struct {
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse []Account

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse Account

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAccountRequestObject struct {
	Id int `json:"id"`
}

type DeleteAccountResponseObject interface {
	VisitDeleteAccountResponse(w http.ResponseWriter) error
}

type DeleteAccount204Response struct {
}

func (response DeleteAccount204Response) VisitDeleteAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAccount404Response struct {
}

func (response DeleteAccount404Response) VisitDeleteAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAccountRequestObject struct {
	Id int `json:"id"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse Account

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount404Response struct {
}

func (response GetAccount404Response) VisitGetAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateAccountRequestObject struct {
	Id   int `json:"id"`
	Body *UpdateAccountJSONRequestBody
}

type UpdateAccountResponseObject interface {
	VisitUpdateAccountResponse(w http.ResponseWriter) error
}

type UpdateAccount200JSONResponse Account

func (response UpdateAccount200JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount404Response struct {
}

func (response UpdateAccount404Response) VisitUpdateAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListAccountSnapshotsRequestObject struct {
	Id int `json:"id"`
}

type ListAccountSnapshotsResponseObject interface {
	VisitListAccountSnapshotsResponse(w http.ResponseWriter) error
}

type ListAccountSnapshots200JSONResponse []AccountSnapshot

func (response ListAccountSnapshots200JSONResponse) VisitListAccountSnapshotsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountSnapshotRequestObject struct {
	Id   int `json:"id"`
	Body *CreateAccountSnapshotJSONRequestBody
}

type CreateAccountSnapshotResponseObject interface {
	VisitCreateAccountSnapshotResponse(w http.ResponseWriter) error
}

type CreateAccountSnapshot201JSONResponse AccountSnapshot

func (response CreateAccountSnapshot201JSONResponse) VisitCreateAccountSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountSnapshot404Response struct {
}

func (response CreateAccountSnapshot404Response) VisitCreateAccountSnapshotResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DeleteAccountSnapshotRequestObject struct {
	Id         int `json:"id"`
	SnapshotId int `json:"snapshotId"`
}

type DeleteAccountSnapshotResponseObject interface {
	VisitDeleteAccountSnapshotResponse(w http.ResponseWriter) error
}

type DeleteAccountSnapshot204Response struct {
}

func (response DeleteAccountSnapshot204Response) VisitDeleteAccountSnapshotResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAccountSnapshot404Response struct {
}

func (response DeleteAccountSnapshot404Response) VisitDeleteAccountSnapshotResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateAccountSnapshotRequestObject struct {
	Id         int `json:"id"`
	SnapshotId int `json:"snapshotId"`
	Body       *UpdateAccountSnapshotJSONRequestBody
}

type UpdateAccountSnapshotResponseObject interface {
	VisitUpdateAccountSnapshotResponse(w http.ResponseWriter) error
}

type UpdateAccountSnapshot200JSONResponse AccountSnapshot

func (response UpdateAccountSnapshot200JSONResponse) VisitUpdateAccountSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccountSnapshot404Response struct {
}

func (response UpdateAccountSnapshot404Response) VisitUpdateAccountSnapshotResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetNetWorthSummaryRequestObject struct {
}

type GetNetWorthSummaryResponseObject interface {
	VisitGetNetWorthSummaryResponse(w http.ResponseWriter) error
}

type GetNetWorthSummary200JSONResponse NetWorthSummary

func (response GetNetWorthSummary200JSONResponse) VisitGetNetWorthSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNetWorthTrendRequestObject struct {
}

type GetNetWorthTrendResponseObject interface {
	VisitGetNetWorthTrendResponse(w http.ResponseWriter) error
}

type GetNetWorthTrend200JSONResponse []NetWorthTrendPoint

func (response GetNetWorthTrend200JSONResponse) VisitGetNetWorthTrendResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)

	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)

	// (DELETE /accounts/{id})
	DeleteAccount(ctx context.Context, request DeleteAccountRequestObject) (DeleteAccountResponseObject, error)

	// (GET /accounts/{id})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)

	// (PUT /accounts/{id})
	UpdateAccount(ctx context.Context, request UpdateAccountRequestObject) (UpdateAccountResponseObject, error)

	// (GET /accounts/{id}/snapshots)
	ListAccountSnapshots(ctx context.Context, request ListAccountSnapshotsRequestObject) (ListAccountSnapshotsResponseObject, error)

	// (POST /accounts/{id}/snapshots)
	CreateAccountSnapshot(ctx context.Context, request CreateAccountSnapshotRequestObject) (CreateAccountSnapshotResponseObject, error)

	// (DELETE /accounts/{id}/snapshots/{snapshotId})
	DeleteAccountSnapshot(ctx context.Context, request DeleteAccountSnapshotRequestObject) (DeleteAccountSnapshotResponseObject, error)

	// (PUT /accounts/{id}/snapshots/{snapshotId})
	UpdateAccountSnapshot(ctx context.Context, request UpdateAccountSnapshotRequestObject) (UpdateAccountSnapshotResponseObject, error)

	// (GET /net-worth/summary)
	GetNetWorthSummary(ctx context.Context, request GetNetWorthSummaryRequestObject) (GetNetWorthSummaryResponseObject, error)

	// (GET /net-worth/trend)
	GetNetWorthTrend(ctx context.Context, request GetNetWorthTrendRequestObject) (GetNetWorthTrendResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request) {
	var request ListAccountsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAccount operation middleware
func (sh *strictHandler) DeleteAccount(w http.ResponseWriter, r *http.Request, id int) {
	var request DeleteAccountRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAccount(ctx, request.(DeleteAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAccountResponseObject); ok {
		if err := validResponse.VisitDeleteAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, id int) {
	var request GetAccountRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAccount operation middleware
func (sh *strictHandler) UpdateAccount(w http.ResponseWriter, r *http.Request, id int) {
	var request UpdateAccountRequestObject

	request.Id = id

	var body UpdateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAccount(ctx, request.(UpdateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAccountResponseObject); ok {
		if err := validResponse.VisitUpdateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAccountSnapshots operation middleware
func (sh *strictHandler) ListAccountSnapshots(w http.ResponseWriter, r *http.Request, id int) {
	var request ListAccountSnapshotsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccountSnapshots(ctx, request.(ListAccountSnapshotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccountSnapshots")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountSnapshotsResponseObject); ok {
		if err := validResponse.VisitListAccountSnapshotsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccountSnapshot operation middleware
func (sh *strictHandler) CreateAccountSnapshot(w http.ResponseWriter, r *http.Request, id int) {
	var request CreateAccountSnapshotRequestObject

	request.Id = id

	var body CreateAccountSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccountSnapshot(ctx, request.(CreateAccountSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccountSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountSnapshotResponseObject); ok {
		if err := validResponse.VisitCreateAccountSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAccountSnapshot operation middleware
func (sh *strictHandler) DeleteAccountSnapshot(w http.ResponseWriter, r *http.Request, id int, snapshotId int) {
	var request DeleteAccountSnapshotRequestObject

	request.Id = id
	request.SnapshotId = snapshotId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAccountSnapshot(ctx, request.(DeleteAccountSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAccountSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAccountSnapshotResponseObject); ok {
		if err := validResponse.VisitDeleteAccountSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAccountSnapshot operation middleware
func (sh *strictHandler) UpdateAccountSnapshot(w http.ResponseWriter, r *http.Request, id int, snapshotId int) {
	var request UpdateAccountSnapshotRequestObject

	request.Id = id
	request.SnapshotId = snapshotId

	var body UpdateAccountSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAccountSnapshot(ctx, request.(UpdateAccountSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAccountSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAccountSnapshotResponseObject); ok {
		if err := validResponse.VisitUpdateAccountSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNetWorthSummary operation middleware
func (sh *strictHandler) GetNetWorthSummary(w http.ResponseWriter, r *http.Request) {
	var request GetNetWorthSummaryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNetWorthSummary(ctx, request.(GetNetWorthSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNetWorthSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNetWorthSummaryResponseObject); ok {
		if err := validResponse.VisitGetNetWorthSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNetWorthTrend operation middleware
func (sh *strictHandler) GetNetWorthTrend(w http.ResponseWriter, r *http.Request) {
	var request GetNetWorthTrendRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNetWorthTrend(ctx, request.(GetNetWorthTrendRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNetWorthTrend")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNetWorthTrendResponseObject); ok {
		if err := validResponse.VisitGetNetWorthTrendResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
