// Code generated by ent, DO NOT EDIT.

package account

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldIsAsset holds the string denoting the is_asset field in the database.
	FieldIsAsset = "is_asset"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldExternalAccountID holds the string denoting the external_account_id field in the database.
	FieldExternalAccountID = "external_account_id"
	// FieldCreditLimit holds the string denoting the credit_limit field in the database.
	FieldCreditLimit = "credit_limit"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// EdgeSnapshots holds the string denoting the snapshots edge name in mutations.
	EdgeSnapshots = "snapshots"
	// EdgeTransactions holds the string denoting the transactions edge name in mutations.
	EdgeTransactions = "transactions"
	// EdgeRecurringItems holds the string denoting the recurring_items edge name in mutations.
	EdgeRecurringItems = "recurring_items"
	// Table holds the table name of the account in the database.
	Table = "accounts"
	// SnapshotsTable is the table that holds the snapshots relation/edge.
	SnapshotsTable = "account_snapshots"
	// SnapshotsInverseTable is the table name for the AccountSnapshot entity.
	// It exists in this package in order to avoid circular dependency with the "accountsnapshot" package.
	SnapshotsInverseTable = "account_snapshots"
	// SnapshotsColumn is the table column denoting the snapshots relation/edge.
	SnapshotsColumn = "account_snapshots"
	// TransactionsTable is the table that holds the transactions relation/edge.
	TransactionsTable = "transactions"
	// TransactionsInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionsInverseTable = "transactions"
	// TransactionsColumn is the table column denoting the transactions relation/edge.
	TransactionsColumn = "account_transactions"
	// RecurringItemsTable is the table that holds the recurring_items relation/edge.
	RecurringItemsTable = "recurring_items"
	// RecurringItemsInverseTable is the table name for the RecurringItem entity.
	// It exists in this package in order to avoid circular dependency with the "recurringitem" package.
	RecurringItemsInverseTable = "recurring_items"
	// RecurringItemsColumn is the table column denoting the recurring_items relation/edge.
	RecurringItemsColumn = "account_recurring_items"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldType,
	FieldIsAsset,
	FieldSource,
	FieldExternalAccountID,
	FieldCreditLimit,
	FieldCreatedAt,
	FieldStatus,
	FieldClosedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeChecking   Type = "checking"
	TypeSavings    Type = "savings"
	TypeCreditCard Type = "credit_card"
	TypeInvestment Type = "investment"
	TypeRealEstate Type = "real_estate"
	TypeVehicle    Type = "vehicle"
	TypeLoan       Type = "loan"
	TypeOtherAsset Type = "other_asset"
	TypeOtherDebt  Type = "other_debt"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeChecking, TypeSavings, TypeCreditCard, TypeInvestment, TypeRealEstate, TypeVehicle, TypeLoan, TypeOtherAsset, TypeOtherDebt:
		return nil
	default:
		return fmt.Errorf("account: invalid enum value for type field: %q", _type)
	}
}

// Source defines the type for the "source" enum field.
type Source string

// SourceManual is the default value of the Source enum.
const DefaultSource = SourceManual

// Source values.
const (
	SourceManual    Source = "manual"
	SourceSimplefin Source = "simplefin"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceManual, SourceSimplefin:
		return nil
	default:
		return fmt.Errorf("account: invalid enum value for source field: %q", s)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive Status = "active"
	StatusClosed Status = "closed"
	StatusHidden Status = "hidden"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusClosed, StatusHidden:
		return nil
	default:
		return fmt.Errorf("account: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByIsAsset orders the results by the is_asset field.
func ByIsAsset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAsset, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByExternalAccountID orders the results by the external_account_id field.
func ByExternalAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalAccountID, opts...).ToFunc()
}

// ByCreditLimit orders the results by the credit_limit field.
func ByCreditLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditLimit, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// BySnapshotsCount orders the results by snapshots count.
func BySnapshotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSnapshotsStep(), opts...)
	}
}

// BySnapshots orders the results by snapshots terms.
func BySnapshots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSnapshotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTransactionsCount orders the results by transactions count.
func ByTransactionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTransactionsStep(), opts...)
	}
}

// ByTransactions orders the results by transactions terms.
func ByTransactions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransactionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRecurringItemsCount orders the results by recurring_items count.
func ByRecurringItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecurringItemsStep(), opts...)
	}
}

// ByRecurringItems orders the results by recurring_items terms.
func ByRecurringItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecurringItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSnapshotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SnapshotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
	)
}
func newTransactionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TransactionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
	)
}
func newRecurringItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecurringItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecurringItemsTable, RecurringItemsColumn),
	)
}
