// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldName, v))
}

// IsAsset applies equality check predicate on the "is_asset" field. It's identical to IsAssetEQ.
func IsAsset(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsAsset, v))
}

// ExternalAccountID applies equality check predicate on the "external_account_id" field. It's identical to ExternalAccountIDEQ.
func ExternalAccountID(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldExternalAccountID, v))
}

// CreditLimit applies equality check predicate on the "credit_limit" field. It's identical to CreditLimitEQ.
func CreditLimit(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreditLimit, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldType, vs...))
}

// IsAssetEQ applies the EQ predicate on the "is_asset" field.
func IsAssetEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsAsset, v))
}

// IsAssetNEQ applies the NEQ predicate on the "is_asset" field.
func IsAssetNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldIsAsset, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSource, vs...))
}

// ExternalAccountIDEQ applies the EQ predicate on the "external_account_id" field.
func ExternalAccountIDEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldExternalAccountID, v))
}

// ExternalAccountIDNEQ applies the NEQ predicate on the "external_account_id" field.
func ExternalAccountIDNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldExternalAccountID, v))
}

// ExternalAccountIDIn applies the In predicate on the "external_account_id" field.
func ExternalAccountIDIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldExternalAccountID, vs...))
}

// ExternalAccountIDNotIn applies the NotIn predicate on the "external_account_id" field.
func ExternalAccountIDNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldExternalAccountID, vs...))
}

// ExternalAccountIDGT applies the GT predicate on the "external_account_id" field.
func ExternalAccountIDGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldExternalAccountID, v))
}

// ExternalAccountIDGTE applies the GTE predicate on the "external_account_id" field.
func ExternalAccountIDGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldExternalAccountID, v))
}

// ExternalAccountIDLT applies the LT predicate on the "external_account_id" field.
func ExternalAccountIDLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldExternalAccountID, v))
}

// ExternalAccountIDLTE applies the LTE predicate on the "external_account_id" field.
func ExternalAccountIDLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldExternalAccountID, v))
}

// ExternalAccountIDContains applies the Contains predicate on the "external_account_id" field.
func ExternalAccountIDContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldExternalAccountID, v))
}

// ExternalAccountIDHasPrefix applies the HasPrefix predicate on the "external_account_id" field.
func ExternalAccountIDHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldExternalAccountID, v))
}

// ExternalAccountIDHasSuffix applies the HasSuffix predicate on the "external_account_id" field.
func ExternalAccountIDHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldExternalAccountID, v))
}

// ExternalAccountIDIsNil applies the IsNil predicate on the "external_account_id" field.
func ExternalAccountIDIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldExternalAccountID))
}

// ExternalAccountIDNotNil applies the NotNil predicate on the "external_account_id" field.
func ExternalAccountIDNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldExternalAccountID))
}

// ExternalAccountIDEqualFold applies the EqualFold predicate on the "external_account_id" field.
func ExternalAccountIDEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldExternalAccountID, v))
}

// ExternalAccountIDContainsFold applies the ContainsFold predicate on the "external_account_id" field.
func ExternalAccountIDContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldExternalAccountID, v))
}

// CreditLimitEQ applies the EQ predicate on the "credit_limit" field.
func CreditLimitEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreditLimit, v))
}

// CreditLimitNEQ applies the NEQ predicate on the "credit_limit" field.
func CreditLimitNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreditLimit, v))
}

// CreditLimitIn applies the In predicate on the "credit_limit" field.
func CreditLimitIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreditLimit, vs...))
}

// CreditLimitNotIn applies the NotIn predicate on the "credit_limit" field.
func CreditLimitNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreditLimit, vs...))
}

// CreditLimitGT applies the GT predicate on the "credit_limit" field.
func CreditLimitGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreditLimit, v))
}

// CreditLimitGTE applies the GTE predicate on the "credit_limit" field.
func CreditLimitGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreditLimit, v))
}

// CreditLimitLT applies the LT predicate on the "credit_limit" field.
func CreditLimitLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreditLimit, v))
}

// CreditLimitLTE applies the LTE predicate on the "credit_limit" field.
func CreditLimitLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreditLimit, v))
}

// CreditLimitIsNil applies the IsNil predicate on the "credit_limit" field.
func CreditLimitIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldCreditLimit))
}

// CreditLimitNotNil applies the NotNil predicate on the "credit_limit" field.
func CreditLimitNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldCreditLimit))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSnapshots applies the HasEdge predicate on the "snapshots" edge.
func HasSnapshots() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotsWith applies the HasEdge predicate on the "snapshots" edge with a given conditions (other predicates).
func HasSnapshotsWith(preds ...predicate.AccountSnapshot) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransactions applies the HasEdge predicate on the "transactions" edge.
func HasTransactions() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionsWith applies the HasEdge predicate on the "transactions" edge with a given conditions (other predicates).
func HasTransactionsWith(preds ...predicate.Transaction) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newTransactionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecurringItems applies the HasEdge predicate on the "recurring_items" edge.
func HasRecurringItems() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecurringItemsTable, RecurringItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecurringItemsWith applies the HasEdge predicate on the "recurring_items" edge with a given conditions (other predicates).
func HasRecurringItemsWith(preds ...predicate.RecurringItem) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newRecurringItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
