// Code generated by ent, DO NOT EDIT.

package accountsnapshot

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the accountsnapshot type in the database.
	Label = "account_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldAsOfDate holds the string denoting the as_of_date field in the database.
	FieldAsOfDate = "as_of_date"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the accountsnapshot in the database.
	Table = "account_snapshots"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "account_snapshots"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_snapshots"
)

// Columns holds all SQL columns for accountsnapshot fields.
var Columns = []string{
	FieldID,
	FieldBalance,
	FieldAsOfDate,
	FieldSource,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "account_snapshots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_snapshots",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Source defines the type for the "source" enum field.
type Source string

// SourceManual is the default value of the Source enum.
const DefaultSource = SourceManual

// Source values.
const (
	SourceManual    Source = "manual"
	SourceSimplefin Source = "simplefin"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceManual, SourceSimplefin:
		return nil
	default:
		return fmt.Errorf("accountsnapshot: invalid enum value for source field: %q", s)
	}
}

// OrderOption defines the ordering options for the AccountSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByAsOfDate orders the results by the as_of_date field.
func ByAsOfDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAsOfDate, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
