// Code generated by ent, DO NOT EDIT.

package accountsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldID, id))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldBalance, v))
}

// AsOfDate applies equality check predicate on the "as_of_date" field. It's identical to AsOfDateEQ.
func AsOfDate(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldAsOfDate, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldBalance, v))
}

// AsOfDateEQ applies the EQ predicate on the "as_of_date" field.
func AsOfDateEQ(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldAsOfDate, v))
}

// AsOfDateNEQ applies the NEQ predicate on the "as_of_date" field.
func AsOfDateNEQ(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldAsOfDate, v))
}

// AsOfDateIn applies the In predicate on the "as_of_date" field.
func AsOfDateIn(vs ...time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldAsOfDate, vs...))
}

// AsOfDateNotIn applies the NotIn predicate on the "as_of_date" field.
func AsOfDateNotIn(vs ...time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldAsOfDate, vs...))
}

// AsOfDateGT applies the GT predicate on the "as_of_date" field.
func AsOfDateGT(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldAsOfDate, v))
}

// AsOfDateGTE applies the GTE predicate on the "as_of_date" field.
func AsOfDateGTE(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldAsOfDate, v))
}

// AsOfDateLT applies the LT predicate on the "as_of_date" field.
func AsOfDateLT(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldAsOfDate, v))
}

// AsOfDateLTE applies the LTE predicate on the "as_of_date" field.
func AsOfDateLTE(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldAsOfDate, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldSource, vs...))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountSnapshot {
	return predicate.AccountSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountSnapshot) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountSnapshot) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountSnapshot) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.NotPredicates(p))
}
