// Code generated by ent, DO NOT EDIT.

package recurringitem

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the recurringitem type in the database.
	Label = "recurring_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFrequency holds the string denoting the frequency field in the database.
	FieldFrequency = "frequency"
	// FieldEstimatedAmount holds the string denoting the estimated_amount field in the database.
	FieldEstimatedAmount = "estimated_amount"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeInstances holds the string denoting the instances edge name in mutations.
	EdgeInstances = "instances"
	// Table holds the table name of the recurringitem in the database.
	Table = "recurring_items"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "recurring_items"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_recurring_items"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "recurring_items"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_recurring_items"
	// InstancesTable is the table that holds the instances relation/edge.
	InstancesTable = "recurring_instances"
	// InstancesInverseTable is the table name for the RecurringInstance entity.
	// It exists in this package in order to avoid circular dependency with the "recurringinstance" package.
	InstancesInverseTable = "recurring_instances"
	// InstancesColumn is the table column denoting the instances relation/edge.
	InstancesColumn = "recurring_item_instances"
)

// Columns holds all SQL columns for recurringitem fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldName,
	FieldFrequency,
	FieldEstimatedAmount,
	FieldStartDate,
	FieldActive,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "recurring_items"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_recurring_items",
	"category_recurring_items",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindExpense                Kind = "expense"
	KindInvestmentContribution Kind = "investment_contribution"
	KindIncome                 Kind = "income"
	KindTransfer               Kind = "transfer"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindExpense, KindInvestmentContribution, KindIncome, KindTransfer:
		return nil
	default:
		return fmt.Errorf("recurringitem: invalid enum value for kind field: %q", k)
	}
}

// Frequency defines the type for the "frequency" enum field.
type Frequency string

// Frequency values.
const (
	FrequencyWeekly         Frequency = "weekly"
	FrequencyBiweekly       Frequency = "biweekly"
	FrequencyMonthly        Frequency = "monthly"
	FrequencyAnnual         Frequency = "annual"
	FrequencyCustomInterval Frequency = "custom_interval"
)

func (f Frequency) String() string {
	return string(f)
}

// FrequencyValidator is a validator for the "frequency" field enum values. It is called by the builders before save.
func FrequencyValidator(f Frequency) error {
	switch f {
	case FrequencyWeekly, FrequencyBiweekly, FrequencyMonthly, FrequencyAnnual, FrequencyCustomInterval:
		return nil
	default:
		return fmt.Errorf("recurringitem: invalid enum value for frequency field: %q", f)
	}
}

// OrderOption defines the ordering options for the RecurringItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByFrequency orders the results by the frequency field.
func ByFrequency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrequency, opts...).ToFunc()
}

// ByEstimatedAmount orders the results by the estimated_amount field.
func ByEstimatedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedAmount, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByInstancesCount orders the results by instances count.
func ByInstancesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInstancesStep(), opts...)
	}
}

// ByInstances orders the results by instances terms.
func ByInstances(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInstancesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
func newInstancesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InstancesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InstancesTable, InstancesColumn),
	)
}
