// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"checking", "savings", "credit_card", "investment", "real_estate", "vehicle", "loan", "other_asset", "other_debt"}},
		{Name: "is_asset", Type: field.TypeBool},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"manual", "simplefin"}, Default: "manual"},
		{Name: "external_account_id", Type: field.TypeString, Nullable: true},
		{Name: "credit_limit", Type: field.TypeFloat64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// AccountSnapshotsColumns holds the columns for the "account_snapshots" table.
	AccountSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "balance", Type: field.TypeFloat64},
		{Name: "as_of_date", Type: field.TypeTime},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"manual", "simplefin"}, Default: "manual"},
		{Name: "account_snapshots", Type: field.TypeInt},
	}
	// AccountSnapshotsTable holds the schema information for the "account_snapshots" table.
	AccountSnapshotsTable = &schema.Table{
		Name:       "account_snapshots",
		Columns:    AccountSnapshotsColumns,
		PrimaryKey: []*schema.Column{AccountSnapshotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_snapshots_accounts_snapshots",
				Columns:    []*schema.Column{AccountSnapshotsColumns[4]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"spending", "income"}},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// RecurringInstancesColumns holds the columns for the "recurring_instances" table.
	RecurringInstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "due_date", Type: field.TypeTime},
		{Name: "estimated_amount", Type: field.TypeFloat64},
		{Name: "actual_amount", Type: field.TypeFloat64, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"upcoming", "estimated", "confirmed", "paid"}, Default: "upcoming"},
		{Name: "recurring_item_instances", Type: field.TypeInt},
	}
	// RecurringInstancesTable holds the schema information for the "recurring_instances" table.
	RecurringInstancesTable = &schema.Table{
		Name:       "recurring_instances",
		Columns:    RecurringInstancesColumns,
		PrimaryKey: []*schema.Column{RecurringInstancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recurring_instances_recurring_items_instances",
				Columns:    []*schema.Column{RecurringInstancesColumns[5]},
				RefColumns: []*schema.Column{RecurringItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RecurringItemsColumns holds the columns for the "recurring_items" table.
	RecurringItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"expense", "investment_contribution", "income", "transfer"}},
		{Name: "name", Type: field.TypeString},
		{Name: "frequency", Type: field.TypeEnum, Enums: []string{"weekly", "biweekly", "monthly", "annual", "custom_interval"}},
		{Name: "estimated_amount", Type: field.TypeFloat64},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "account_recurring_items", Type: field.TypeInt, Nullable: true},
		{Name: "category_recurring_items", Type: field.TypeInt, Nullable: true},
	}
	// RecurringItemsTable holds the schema information for the "recurring_items" table.
	RecurringItemsTable = &schema.Table{
		Name:       "recurring_items",
		Columns:    RecurringItemsColumns,
		PrimaryKey: []*schema.Column{RecurringItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recurring_items_accounts_recurring_items",
				Columns:    []*schema.Column{RecurringItemsColumns[7]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "recurring_items_categories_recurring_items",
				Columns:    []*schema.Column{RecurringItemsColumns[8]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "posted_date", Type: field.TypeTime},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"manual", "simplefin"}, Default: "manual"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"provisional", "confirmed"}, Default: "provisional"},
		{Name: "external_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "classification", Type: field.TypeEnum, Enums: []string{"discretionary", "recurring_fulfillment", "transfer", "income"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "account_transactions", Type: field.TypeInt},
		{Name: "category_transactions", Type: field.TypeInt, Nullable: true},
		{Name: "recurring_instance_transaction", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "transaction_transfer_pair", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_accounts_transactions",
				Columns:    []*schema.Column{TransactionsColumns[9]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transactions_categories_transactions",
				Columns:    []*schema.Column{TransactionsColumns[10]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "transactions_recurring_instances_transaction",
				Columns:    []*schema.Column{TransactionsColumns[11]},
				RefColumns: []*schema.Column{RecurringInstancesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "transactions_transactions_transfer_pair",
				Columns:    []*schema.Column{TransactionsColumns[12]},
				RefColumns: []*schema.Column{TransactionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		AccountSnapshotsTable,
		CategoriesTable,
		RecurringInstancesTable,
		RecurringItemsTable,
		TransactionsTable,
	}
)

func init() {
	AccountSnapshotsTable.ForeignKeys[0].RefTable = AccountsTable
	RecurringInstancesTable.ForeignKeys[0].RefTable = RecurringItemsTable
	RecurringItemsTable.ForeignKeys[0].RefTable = AccountsTable
	RecurringItemsTable.ForeignKeys[1].RefTable = CategoriesTable
	TransactionsTable.ForeignKeys[0].RefTable = AccountsTable
	TransactionsTable.ForeignKeys[1].RefTable = CategoriesTable
	TransactionsTable.ForeignKeys[2].RefTable = RecurringInstancesTable
	TransactionsTable.ForeignKeys[3].RefTable = TransactionsTable
}
