// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/accountsnapshot"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringitem"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/transaction"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdate) SetName(v string) *AccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableName(v *string) *AccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AccountUpdate) SetType(v account.Type) *AccountUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableType(v *account.Type) *AccountUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetIsAsset sets the "is_asset" field.
func (_u *AccountUpdate) SetIsAsset(v bool) *AccountUpdate {
	_u.mutation.SetIsAsset(v)
	return _u
}

// SetNillableIsAsset sets the "is_asset" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsAsset(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsAsset(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *AccountUpdate) SetSource(v account.Source) *AccountUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableSource(v *account.Source) *AccountUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetExternalAccountID sets the "external_account_id" field.
func (_u *AccountUpdate) SetExternalAccountID(v string) *AccountUpdate {
	_u.mutation.SetExternalAccountID(v)
	return _u
}

// SetNillableExternalAccountID sets the "external_account_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableExternalAccountID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetExternalAccountID(*v)
	}
	return _u
}

// ClearExternalAccountID clears the value of the "external_account_id" field.
func (_u *AccountUpdate) ClearExternalAccountID() *AccountUpdate {
	_u.mutation.ClearExternalAccountID()
	return _u
}

// SetCreditLimit sets the "credit_limit" field.
func (_u *AccountUpdate) SetCreditLimit(v float64) *AccountUpdate {
	_u.mutation.ResetCreditLimit()
	_u.mutation.SetCreditLimit(v)
	return _u
}

// SetNillableCreditLimit sets the "credit_limit" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableCreditLimit(v *float64) *AccountUpdate {
	if v != nil {
		_u.SetCreditLimit(*v)
	}
	return _u
}

// AddCreditLimit adds value to the "credit_limit" field.
func (_u *AccountUpdate) AddCreditLimit(v float64) *AccountUpdate {
	_u.mutation.AddCreditLimit(v)
	return _u
}

// ClearCreditLimit clears the value of the "credit_limit" field.
func (_u *AccountUpdate) ClearCreditLimit() *AccountUpdate {
	_u.mutation.ClearCreditLimit()
	return _u
}

// AddSnapshotIDs adds the "snapshots" edge to the AccountSnapshot entity by IDs.
func (_u *AccountUpdate) AddSnapshotIDs(ids ...int) *AccountUpdate {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the AccountSnapshot entity.
func (_u *AccountUpdate) AddSnapshots(v ...*AccountSnapshot) *AccountUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *AccountUpdate) AddTransactionIDs(ids ...int) *AccountUpdate {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *AccountUpdate) AddTransactions(v ...*Transaction) *AccountUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddRecurringItemIDs adds the "recurring_items" edge to the RecurringItem entity by IDs.
func (_u *AccountUpdate) AddRecurringItemIDs(ids ...int) *AccountUpdate {
	_u.mutation.AddRecurringItemIDs(ids...)
	return _u
}

// AddRecurringItems adds the "recurring_items" edges to the RecurringItem entity.
func (_u *AccountUpdate) AddRecurringItems(v ...*RecurringItem) *AccountUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecurringItemIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearSnapshots clears all "snapshots" edges to the AccountSnapshot entity.
func (_u *AccountUpdate) ClearSnapshots() *AccountUpdate {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to AccountSnapshot entities by IDs.
func (_u *AccountUpdate) RemoveSnapshotIDs(ids ...int) *AccountUpdate {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to AccountSnapshot entities.
func (_u *AccountUpdate) RemoveSnapshots(v ...*AccountSnapshot) *AccountUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *AccountUpdate) ClearTransactions() *AccountUpdate {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *AccountUpdate) RemoveTransactionIDs(ids ...int) *AccountUpdate {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *AccountUpdate) RemoveTransactions(v ...*Transaction) *AccountUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearRecurringItems clears all "recurring_items" edges to the RecurringItem entity.
func (_u *AccountUpdate) ClearRecurringItems() *AccountUpdate {
	_u.mutation.ClearRecurringItems()
	return _u
}

// RemoveRecurringItemIDs removes the "recurring_items" edge to RecurringItem entities by IDs.
func (_u *AccountUpdate) RemoveRecurringItemIDs(ids ...int) *AccountUpdate {
	_u.mutation.RemoveRecurringItemIDs(ids...)
	return _u
}

// RemoveRecurringItems removes "recurring_items" edges to RecurringItem entities.
func (_u *AccountUpdate) RemoveRecurringItems(v ...*RecurringItem) *AccountUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecurringItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := account.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Account.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := account.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Account.source": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsAsset(); ok {
		_spec.SetField(account.FieldIsAsset, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(account.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExternalAccountID(); ok {
		_spec.SetField(account.FieldExternalAccountID, field.TypeString, value)
	}
	if _u.mutation.ExternalAccountIDCleared() {
		_spec.ClearField(account.FieldExternalAccountID, field.TypeString)
	}
	if value, ok := _u.mutation.CreditLimit(); ok {
		_spec.SetField(account.FieldCreditLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditLimit(); ok {
		_spec.AddField(account.FieldCreditLimit, field.TypeFloat64, value)
	}
	if _u.mutation.CreditLimitCleared() {
		_spec.ClearField(account.FieldCreditLimit, field.TypeFloat64)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SnapshotsTable,
			Columns: []string{account.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SnapshotsTable,
			Columns: []string{account.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SnapshotsTable,
			Columns: []string{account.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TransactionsTable,
			Columns: []string{account.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TransactionsTable,
			Columns: []string{account.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TransactionsTable,
			Columns: []string{account.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecurringItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.RecurringItemsTable,
			Columns: []string{account.RecurringItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecurringItemsIDs(); len(nodes) > 0 && !_u.mutation.RecurringItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.RecurringItemsTable,
			Columns: []string{account.RecurringItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.RecurringItemsTable,
			Columns: []string{account.RecurringItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetName sets the "name" field.
func (_u *AccountUpdateOne) SetName(v string) *AccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableName(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AccountUpdateOne) SetType(v account.Type) *AccountUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableType(v *account.Type) *AccountUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetIsAsset sets the "is_asset" field.
func (_u *AccountUpdateOne) SetIsAsset(v bool) *AccountUpdateOne {
	_u.mutation.SetIsAsset(v)
	return _u
}

// SetNillableIsAsset sets the "is_asset" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsAsset(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsAsset(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *AccountUpdateOne) SetSource(v account.Source) *AccountUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableSource(v *account.Source) *AccountUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetExternalAccountID sets the "external_account_id" field.
func (_u *AccountUpdateOne) SetExternalAccountID(v string) *AccountUpdateOne {
	_u.mutation.SetExternalAccountID(v)
	return _u
}

// SetNillableExternalAccountID sets the "external_account_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableExternalAccountID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetExternalAccountID(*v)
	}
	return _u
}

// ClearExternalAccountID clears the value of the "external_account_id" field.
func (_u *AccountUpdateOne) ClearExternalAccountID() *AccountUpdateOne {
	_u.mutation.ClearExternalAccountID()
	return _u
}

// SetCreditLimit sets the "credit_limit" field.
func (_u *AccountUpdateOne) SetCreditLimit(v float64) *AccountUpdateOne {
	_u.mutation.ResetCreditLimit()
	_u.mutation.SetCreditLimit(v)
	return _u
}

// SetNillableCreditLimit sets the "credit_limit" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableCreditLimit(v *float64) *AccountUpdateOne {
	if v != nil {
		_u.SetCreditLimit(*v)
	}
	return _u
}

// AddCreditLimit adds value to the "credit_limit" field.
func (_u *AccountUpdateOne) AddCreditLimit(v float64) *AccountUpdateOne {
	_u.mutation.AddCreditLimit(v)
	return _u
}

// ClearCreditLimit clears the value of the "credit_limit" field.
func (_u *AccountUpdateOne) ClearCreditLimit() *AccountUpdateOne {
	_u.mutation.ClearCreditLimit()
	return _u
}

// AddSnapshotIDs adds the "snapshots" edge to the AccountSnapshot entity by IDs.
func (_u *AccountUpdateOne) AddSnapshotIDs(ids ...int) *AccountUpdateOne {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the AccountSnapshot entity.
func (_u *AccountUpdateOne) AddSnapshots(v ...*AccountSnapshot) *AccountUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *AccountUpdateOne) AddTransactionIDs(ids ...int) *AccountUpdateOne {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *AccountUpdateOne) AddTransactions(v ...*Transaction) *AccountUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddRecurringItemIDs adds the "recurring_items" edge to the RecurringItem entity by IDs.
func (_u *AccountUpdateOne) AddRecurringItemIDs(ids ...int) *AccountUpdateOne {
	_u.mutation.AddRecurringItemIDs(ids...)
	return _u
}

// AddRecurringItems adds the "recurring_items" edges to the RecurringItem entity.
func (_u *AccountUpdateOne) AddRecurringItems(v ...*RecurringItem) *AccountUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecurringItemIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearSnapshots clears all "snapshots" edges to the AccountSnapshot entity.
func (_u *AccountUpdateOne) ClearSnapshots() *AccountUpdateOne {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to AccountSnapshot entities by IDs.
func (_u *AccountUpdateOne) RemoveSnapshotIDs(ids ...int) *AccountUpdateOne {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to AccountSnapshot entities.
func (_u *AccountUpdateOne) RemoveSnapshots(v ...*AccountSnapshot) *AccountUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *AccountUpdateOne) ClearTransactions() *AccountUpdateOne {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *AccountUpdateOne) RemoveTransactionIDs(ids ...int) *AccountUpdateOne {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *AccountUpdateOne) RemoveTransactions(v ...*Transaction) *AccountUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearRecurringItems clears all "recurring_items" edges to the RecurringItem entity.
func (_u *AccountUpdateOne) ClearRecurringItems() *AccountUpdateOne {
	_u.mutation.ClearRecurringItems()
	return _u
}

// RemoveRecurringItemIDs removes the "recurring_items" edge to RecurringItem entities by IDs.
func (_u *AccountUpdateOne) RemoveRecurringItemIDs(ids ...int) *AccountUpdateOne {
	_u.mutation.RemoveRecurringItemIDs(ids...)
	return _u
}

// RemoveRecurringItems removes "recurring_items" edges to RecurringItem entities.
func (_u *AccountUpdateOne) RemoveRecurringItems(v ...*RecurringItem) *AccountUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecurringItemIDs(ids...)
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := account.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Account.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := account.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Account.source": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsAsset(); ok {
		_spec.SetField(account.FieldIsAsset, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(account.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExternalAccountID(); ok {
		_spec.SetField(account.FieldExternalAccountID, field.TypeString, value)
	}
	if _u.mutation.ExternalAccountIDCleared() {
		_spec.ClearField(account.FieldExternalAccountID, field.TypeString)
	}
	if value, ok := _u.mutation.CreditLimit(); ok {
		_spec.SetField(account.FieldCreditLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditLimit(); ok {
		_spec.AddField(account.FieldCreditLimit, field.TypeFloat64, value)
	}
	if _u.mutation.CreditLimitCleared() {
		_spec.ClearField(account.FieldCreditLimit, field.TypeFloat64)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SnapshotsTable,
			Columns: []string{account.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SnapshotsTable,
			Columns: []string{account.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SnapshotsTable,
			Columns: []string{account.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TransactionsTable,
			Columns: []string{account.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TransactionsTable,
			Columns: []string{account.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TransactionsTable,
			Columns: []string{account.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecurringItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.RecurringItemsTable,
			Columns: []string{account.RecurringItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecurringItemsIDs(); len(nodes) > 0 && !_u.mutation.RecurringItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.RecurringItemsTable,
			Columns: []string{account.RecurringItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.RecurringItemsTable,
			Columns: []string{account.RecurringItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
