// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/accountsnapshot"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
)

// AccountSnapshotDelete is the builder for deleting a AccountSnapshot entity.
type AccountSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *AccountSnapshotMutation
}

// Where appends a list predicates to the AccountSnapshotDelete builder.
func (_d *AccountSnapshotDelete) Where(ps ...predicate.AccountSnapshot) *AccountSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountsnapshot.Table, sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountSnapshotDeleteOne is the builder for deleting a single AccountSnapshot entity.
type AccountSnapshotDeleteOne struct {
	_d *AccountSnapshotDelete
}

// Where appends a list predicates to the AccountSnapshotDelete builder.
func (_d *AccountSnapshotDeleteOne) Where(ps ...predicate.AccountSnapshot) *AccountSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
