// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/accountsnapshot"
)

// AccountSnapshot is the model entity for the AccountSnapshot schema.
type AccountSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// AsOfDate holds the value of the "as_of_date" field.
	AsOfDate time.Time `json:"as_of_date,omitempty"`
	// Source holds the value of the "source" field.
	Source accountsnapshot.Source `json:"source,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountSnapshotQuery when eager-loading is set.
	Edges             AccountSnapshotEdges `json:"edges"`
	account_snapshots *int
	selectValues      sql.SelectValues
}

// AccountSnapshotEdges holds the relations/edges for other nodes in the graph.
type AccountSnapshotEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountSnapshotEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountsnapshot.FieldBalance:
			values[i] = new(sql.NullFloat64)
		case accountsnapshot.FieldID:
			values[i] = new(sql.NullInt64)
		case accountsnapshot.FieldSource:
			values[i] = new(sql.NullString)
		case accountsnapshot.FieldAsOfDate:
			values[i] = new(sql.NullTime)
		case accountsnapshot.ForeignKeys[0]: // account_snapshots
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountSnapshot fields.
func (_m *AccountSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountsnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case accountsnapshot.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Float64
			}
		case accountsnapshot.FieldAsOfDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field as_of_date", values[i])
			} else if value.Valid {
				_m.AsOfDate = value.Time
			}
		case accountsnapshot.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = accountsnapshot.Source(value.String)
			}
		case accountsnapshot.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field account_snapshots", value)
			} else if value.Valid {
				_m.account_snapshots = new(int)
				*_m.account_snapshots = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *AccountSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountSnapshot entity.
func (_m *AccountSnapshot) QueryAccount() *AccountQuery {
	return NewAccountSnapshotClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this AccountSnapshot.
// Note that you need to call AccountSnapshot.Unwrap() before calling this method if this AccountSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountSnapshot) Update() *AccountSnapshotUpdateOne {
	return NewAccountSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountSnapshot) Unwrap() *AccountSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("AccountSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("as_of_date=")
	builder.WriteString(_m.AsOfDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteByte(')')
	return builder.String()
}

// AccountSnapshots is a parsable slice of AccountSnapshot.
type AccountSnapshots []*AccountSnapshot
