// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/accountsnapshot"
)

// AccountSnapshotCreate is the builder for creating a AccountSnapshot entity.
type AccountSnapshotCreate struct {
	config
	mutation *AccountSnapshotMutation
	hooks    []Hook
}

// SetBalance sets the "balance" field.
func (_c *AccountSnapshotCreate) SetBalance(v float64) *AccountSnapshotCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetAsOfDate sets the "as_of_date" field.
func (_c *AccountSnapshotCreate) SetAsOfDate(v time.Time) *AccountSnapshotCreate {
	_c.mutation.SetAsOfDate(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *AccountSnapshotCreate) SetSource(v accountsnapshot.Source) *AccountSnapshotCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *AccountSnapshotCreate) SetNillableSource(v *accountsnapshot.Source) *AccountSnapshotCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *AccountSnapshotCreate) SetAccountID(id int) *AccountSnapshotCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountSnapshotCreate) SetAccount(v *Account) *AccountSnapshotCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the AccountSnapshotMutation object of the builder.
func (_c *AccountSnapshotCreate) Mutation() *AccountSnapshotMutation {
	return _c.mutation
}

// Save creates the AccountSnapshot in the database.
func (_c *AccountSnapshotCreate) Save(ctx context.Context) (*AccountSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountSnapshotCreate) SaveX(ctx context.Context) *AccountSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountSnapshotCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := accountsnapshot.DefaultSource
		_c.mutation.SetSource(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountSnapshotCreate) check() error {
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "AccountSnapshot.balance"`)}
	}
	if _, ok := _c.mutation.AsOfDate(); !ok {
		return &ValidationError{Name: "as_of_date", err: errors.New(`ent: missing required field "AccountSnapshot.as_of_date"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "AccountSnapshot.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := accountsnapshot.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AccountSnapshot.source": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountSnapshot.account"`)}
	}
	return nil
}

func (_c *AccountSnapshotCreate) sqlSave(ctx context.Context) (*AccountSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountSnapshotCreate) createSpec() (*AccountSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountsnapshot.Table, sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(accountsnapshot.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.AsOfDate(); ok {
		_spec.SetField(accountsnapshot.FieldAsOfDate, field.TypeTime, value)
		_node.AsOfDate = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(accountsnapshot.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountsnapshot.AccountTable,
			Columns: []string{accountsnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_snapshots = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountSnapshotCreateBulk is the builder for creating many AccountSnapshot entities in bulk.
type AccountSnapshotCreateBulk struct {
	config
	err      error
	builders []*AccountSnapshotCreate
}

// Save creates the AccountSnapshot entities in the database.
func (_c *AccountSnapshotCreateBulk) Save(ctx context.Context) ([]*AccountSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountSnapshotCreateBulk) SaveX(ctx context.Context) []*AccountSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
