// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringitem"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/transaction"
)

// RecurringInstanceUpdate is the builder for updating RecurringInstance entities.
type RecurringInstanceUpdate struct {
	config
	hooks    []Hook
	mutation *RecurringInstanceMutation
}

// Where appends a list predicates to the RecurringInstanceUpdate builder.
func (_u *RecurringInstanceUpdate) Where(ps ...predicate.RecurringInstance) *RecurringInstanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *RecurringInstanceUpdate) SetDueDate(v time.Time) *RecurringInstanceUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *RecurringInstanceUpdate) SetNillableDueDate(v *time.Time) *RecurringInstanceUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// SetEstimatedAmount sets the "estimated_amount" field.
func (_u *RecurringInstanceUpdate) SetEstimatedAmount(v float64) *RecurringInstanceUpdate {
	_u.mutation.ResetEstimatedAmount()
	_u.mutation.SetEstimatedAmount(v)
	return _u
}

// SetNillableEstimatedAmount sets the "estimated_amount" field if the given value is not nil.
func (_u *RecurringInstanceUpdate) SetNillableEstimatedAmount(v *float64) *RecurringInstanceUpdate {
	if v != nil {
		_u.SetEstimatedAmount(*v)
	}
	return _u
}

// AddEstimatedAmount adds value to the "estimated_amount" field.
func (_u *RecurringInstanceUpdate) AddEstimatedAmount(v float64) *RecurringInstanceUpdate {
	_u.mutation.AddEstimatedAmount(v)
	return _u
}

// SetActualAmount sets the "actual_amount" field.
func (_u *RecurringInstanceUpdate) SetActualAmount(v float64) *RecurringInstanceUpdate {
	_u.mutation.ResetActualAmount()
	_u.mutation.SetActualAmount(v)
	return _u
}

// SetNillableActualAmount sets the "actual_amount" field if the given value is not nil.
func (_u *RecurringInstanceUpdate) SetNillableActualAmount(v *float64) *RecurringInstanceUpdate {
	if v != nil {
		_u.SetActualAmount(*v)
	}
	return _u
}

// AddActualAmount adds value to the "actual_amount" field.
func (_u *RecurringInstanceUpdate) AddActualAmount(v float64) *RecurringInstanceUpdate {
	_u.mutation.AddActualAmount(v)
	return _u
}

// ClearActualAmount clears the value of the "actual_amount" field.
func (_u *RecurringInstanceUpdate) ClearActualAmount() *RecurringInstanceUpdate {
	_u.mutation.ClearActualAmount()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RecurringInstanceUpdate) SetStatus(v recurringinstance.Status) *RecurringInstanceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RecurringInstanceUpdate) SetNillableStatus(v *recurringinstance.Status) *RecurringInstanceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRecurringItemID sets the "recurring_item" edge to the RecurringItem entity by ID.
func (_u *RecurringInstanceUpdate) SetRecurringItemID(id int) *RecurringInstanceUpdate {
	_u.mutation.SetRecurringItemID(id)
	return _u
}

// SetRecurringItem sets the "recurring_item" edge to the RecurringItem entity.
func (_u *RecurringInstanceUpdate) SetRecurringItem(v *RecurringItem) *RecurringInstanceUpdate {
	return _u.SetRecurringItemID(v.ID)
}

// SetTransactionID sets the "transaction" edge to the Transaction entity by ID.
func (_u *RecurringInstanceUpdate) SetTransactionID(id int) *RecurringInstanceUpdate {
	_u.mutation.SetTransactionID(id)
	return _u
}

// SetNillableTransactionID sets the "transaction" edge to the Transaction entity by ID if the given value is not nil.
func (_u *RecurringInstanceUpdate) SetNillableTransactionID(id *int) *RecurringInstanceUpdate {
	if id != nil {
		_u = _u.SetTransactionID(*id)
	}
	return _u
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (_u *RecurringInstanceUpdate) SetTransaction(v *Transaction) *RecurringInstanceUpdate {
	return _u.SetTransactionID(v.ID)
}

// Mutation returns the RecurringInstanceMutation object of the builder.
func (_u *RecurringInstanceUpdate) Mutation() *RecurringInstanceMutation {
	return _u.mutation
}

// ClearRecurringItem clears the "recurring_item" edge to the RecurringItem entity.
func (_u *RecurringInstanceUpdate) ClearRecurringItem() *RecurringInstanceUpdate {
	_u.mutation.ClearRecurringItem()
	return _u
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (_u *RecurringInstanceUpdate) ClearTransaction() *RecurringInstanceUpdate {
	_u.mutation.ClearTransaction()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecurringInstanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringInstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecurringInstanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringInstanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringInstanceUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := recurringinstance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RecurringInstance.status": %w`, err)}
		}
	}
	if _u.mutation.RecurringItemCleared() && len(_u.mutation.RecurringItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringInstance.recurring_item"`)
	}
	return nil
}

func (_u *RecurringInstanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringinstance.Table, recurringinstance.Columns, sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(recurringinstance.FieldDueDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EstimatedAmount(); ok {
		_spec.SetField(recurringinstance.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedAmount(); ok {
		_spec.AddField(recurringinstance.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualAmount(); ok {
		_spec.SetField(recurringinstance.FieldActualAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualAmount(); ok {
		_spec.AddField(recurringinstance.FieldActualAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ActualAmountCleared() {
		_spec.ClearField(recurringinstance.FieldActualAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(recurringinstance.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.RecurringItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringinstance.RecurringItemTable,
			Columns: []string{recurringinstance.RecurringItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringinstance.RecurringItemTable,
			Columns: []string{recurringinstance.RecurringItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   recurringinstance.TransactionTable,
			Columns: []string{recurringinstance.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   recurringinstance.TransactionTable,
			Columns: []string{recurringinstance.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecurringInstanceUpdateOne is the builder for updating a single RecurringInstance entity.
type RecurringInstanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecurringInstanceMutation
}

// SetDueDate sets the "due_date" field.
func (_u *RecurringInstanceUpdateOne) SetDueDate(v time.Time) *RecurringInstanceUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *RecurringInstanceUpdateOne) SetNillableDueDate(v *time.Time) *RecurringInstanceUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// SetEstimatedAmount sets the "estimated_amount" field.
func (_u *RecurringInstanceUpdateOne) SetEstimatedAmount(v float64) *RecurringInstanceUpdateOne {
	_u.mutation.ResetEstimatedAmount()
	_u.mutation.SetEstimatedAmount(v)
	return _u
}

// SetNillableEstimatedAmount sets the "estimated_amount" field if the given value is not nil.
func (_u *RecurringInstanceUpdateOne) SetNillableEstimatedAmount(v *float64) *RecurringInstanceUpdateOne {
	if v != nil {
		_u.SetEstimatedAmount(*v)
	}
	return _u
}

// AddEstimatedAmount adds value to the "estimated_amount" field.
func (_u *RecurringInstanceUpdateOne) AddEstimatedAmount(v float64) *RecurringInstanceUpdateOne {
	_u.mutation.AddEstimatedAmount(v)
	return _u
}

// SetActualAmount sets the "actual_amount" field.
func (_u *RecurringInstanceUpdateOne) SetActualAmount(v float64) *RecurringInstanceUpdateOne {
	_u.mutation.ResetActualAmount()
	_u.mutation.SetActualAmount(v)
	return _u
}

// SetNillableActualAmount sets the "actual_amount" field if the given value is not nil.
func (_u *RecurringInstanceUpdateOne) SetNillableActualAmount(v *float64) *RecurringInstanceUpdateOne {
	if v != nil {
		_u.SetActualAmount(*v)
	}
	return _u
}

// AddActualAmount adds value to the "actual_amount" field.
func (_u *RecurringInstanceUpdateOne) AddActualAmount(v float64) *RecurringInstanceUpdateOne {
	_u.mutation.AddActualAmount(v)
	return _u
}

// ClearActualAmount clears the value of the "actual_amount" field.
func (_u *RecurringInstanceUpdateOne) ClearActualAmount() *RecurringInstanceUpdateOne {
	_u.mutation.ClearActualAmount()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RecurringInstanceUpdateOne) SetStatus(v recurringinstance.Status) *RecurringInstanceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RecurringInstanceUpdateOne) SetNillableStatus(v *recurringinstance.Status) *RecurringInstanceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRecurringItemID sets the "recurring_item" edge to the RecurringItem entity by ID.
func (_u *RecurringInstanceUpdateOne) SetRecurringItemID(id int) *RecurringInstanceUpdateOne {
	_u.mutation.SetRecurringItemID(id)
	return _u
}

// SetRecurringItem sets the "recurring_item" edge to the RecurringItem entity.
func (_u *RecurringInstanceUpdateOne) SetRecurringItem(v *RecurringItem) *RecurringInstanceUpdateOne {
	return _u.SetRecurringItemID(v.ID)
}

// SetTransactionID sets the "transaction" edge to the Transaction entity by ID.
func (_u *RecurringInstanceUpdateOne) SetTransactionID(id int) *RecurringInstanceUpdateOne {
	_u.mutation.SetTransactionID(id)
	return _u
}

// SetNillableTransactionID sets the "transaction" edge to the Transaction entity by ID if the given value is not nil.
func (_u *RecurringInstanceUpdateOne) SetNillableTransactionID(id *int) *RecurringInstanceUpdateOne {
	if id != nil {
		_u = _u.SetTransactionID(*id)
	}
	return _u
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (_u *RecurringInstanceUpdateOne) SetTransaction(v *Transaction) *RecurringInstanceUpdateOne {
	return _u.SetTransactionID(v.ID)
}

// Mutation returns the RecurringInstanceMutation object of the builder.
func (_u *RecurringInstanceUpdateOne) Mutation() *RecurringInstanceMutation {
	return _u.mutation
}

// ClearRecurringItem clears the "recurring_item" edge to the RecurringItem entity.
func (_u *RecurringInstanceUpdateOne) ClearRecurringItem() *RecurringInstanceUpdateOne {
	_u.mutation.ClearRecurringItem()
	return _u
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (_u *RecurringInstanceUpdateOne) ClearTransaction() *RecurringInstanceUpdateOne {
	_u.mutation.ClearTransaction()
	return _u
}

// Where appends a list predicates to the RecurringInstanceUpdate builder.
func (_u *RecurringInstanceUpdateOne) Where(ps ...predicate.RecurringInstance) *RecurringInstanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecurringInstanceUpdateOne) Select(field string, fields ...string) *RecurringInstanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RecurringInstance entity.
func (_u *RecurringInstanceUpdateOne) Save(ctx context.Context) (*RecurringInstance, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringInstanceUpdateOne) SaveX(ctx context.Context) *RecurringInstance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecurringInstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringInstanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringInstanceUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := recurringinstance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RecurringInstance.status": %w`, err)}
		}
	}
	if _u.mutation.RecurringItemCleared() && len(_u.mutation.RecurringItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringInstance.recurring_item"`)
	}
	return nil
}

func (_u *RecurringInstanceUpdateOne) sqlSave(ctx context.Context) (_node *RecurringInstance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringinstance.Table, recurringinstance.Columns, sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecurringInstance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringinstance.FieldID)
		for _, f := range fields {
			if !recurringinstance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recurringinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(recurringinstance.FieldDueDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EstimatedAmount(); ok {
		_spec.SetField(recurringinstance.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedAmount(); ok {
		_spec.AddField(recurringinstance.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualAmount(); ok {
		_spec.SetField(recurringinstance.FieldActualAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualAmount(); ok {
		_spec.AddField(recurringinstance.FieldActualAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ActualAmountCleared() {
		_spec.ClearField(recurringinstance.FieldActualAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(recurringinstance.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.RecurringItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringinstance.RecurringItemTable,
			Columns: []string{recurringinstance.RecurringItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringinstance.RecurringItemTable,
			Columns: []string{recurringinstance.RecurringItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   recurringinstance.TransactionTable,
			Columns: []string{recurringinstance.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   recurringinstance.TransactionTable,
			Columns: []string{recurringinstance.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RecurringInstance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
