// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/category"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringitem"
)

// RecurringItemCreate is the builder for creating a RecurringItem entity.
type RecurringItemCreate struct {
	config
	mutation *RecurringItemMutation
	hooks    []Hook
}

// SetKind sets the "kind" field.
func (_c *RecurringItemCreate) SetKind(v recurringitem.Kind) *RecurringItemCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RecurringItemCreate) SetName(v string) *RecurringItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *RecurringItemCreate) SetFrequency(v recurringitem.Frequency) *RecurringItemCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetEstimatedAmount sets the "estimated_amount" field.
func (_c *RecurringItemCreate) SetEstimatedAmount(v float64) *RecurringItemCreate {
	_c.mutation.SetEstimatedAmount(v)
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *RecurringItemCreate) SetStartDate(v time.Time) *RecurringItemCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *RecurringItemCreate) SetActive(v bool) *RecurringItemCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *RecurringItemCreate) SetNillableActive(v *bool) *RecurringItemCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *RecurringItemCreate) SetAccountID(id int) *RecurringItemCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (_c *RecurringItemCreate) SetNillableAccountID(id *int) *RecurringItemCreate {
	if id != nil {
		_c = _c.SetAccountID(*id)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *RecurringItemCreate) SetAccount(v *Account) *RecurringItemCreate {
	return _c.SetAccountID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_c *RecurringItemCreate) SetCategoryID(id int) *RecurringItemCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_c *RecurringItemCreate) SetNillableCategoryID(id *int) *RecurringItemCreate {
	if id != nil {
		_c = _c.SetCategoryID(*id)
	}
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *RecurringItemCreate) SetCategory(v *Category) *RecurringItemCreate {
	return _c.SetCategoryID(v.ID)
}

// AddInstanceIDs adds the "instances" edge to the RecurringInstance entity by IDs.
func (_c *RecurringItemCreate) AddInstanceIDs(ids ...int) *RecurringItemCreate {
	_c.mutation.AddInstanceIDs(ids...)
	return _c
}

// AddInstances adds the "instances" edges to the RecurringInstance entity.
func (_c *RecurringItemCreate) AddInstances(v ...*RecurringInstance) *RecurringItemCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInstanceIDs(ids...)
}

// Mutation returns the RecurringItemMutation object of the builder.
func (_c *RecurringItemCreate) Mutation() *RecurringItemMutation {
	return _c.mutation
}

// Save creates the RecurringItem in the database.
func (_c *RecurringItemCreate) Save(ctx context.Context) (*RecurringItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecurringItemCreate) SaveX(ctx context.Context) *RecurringItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecurringItemCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := recurringitem.DefaultActive
		_c.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecurringItemCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "RecurringItem.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := recurringitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RecurringItem.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := recurringitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Frequency(); !ok {
		return &ValidationError{Name: "frequency", err: errors.New(`ent: missing required field "RecurringItem.frequency"`)}
	}
	if v, ok := _c.mutation.Frequency(); ok {
		if err := recurringitem.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.frequency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EstimatedAmount(); !ok {
		return &ValidationError{Name: "estimated_amount", err: errors.New(`ent: missing required field "RecurringItem.estimated_amount"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "RecurringItem.start_date"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "RecurringItem.active"`)}
	}
	return nil
}

func (_c *RecurringItemCreate) sqlSave(ctx context.Context) (*RecurringItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecurringItemCreate) createSpec() (*RecurringItem, *sqlgraph.CreateSpec) {
	var (
		_node = &RecurringItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recurringitem.Table, sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(recurringitem.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(recurringitem.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(recurringitem.FieldFrequency, field.TypeEnum, value)
		_node.Frequency = value
	}
	if value, ok := _c.mutation.EstimatedAmount(); ok {
		_spec.SetField(recurringitem.FieldEstimatedAmount, field.TypeFloat64, value)
		_node.EstimatedAmount = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(recurringitem.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(recurringitem.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.AccountTable,
			Columns: []string{recurringitem.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_recurring_items = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.CategoryTable,
			Columns: []string{recurringitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.category_recurring_items = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recurringitem.InstancesTable,
			Columns: []string{recurringitem.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecurringItemCreateBulk is the builder for creating many RecurringItem entities in bulk.
type RecurringItemCreateBulk struct {
	config
	err      error
	builders []*RecurringItemCreate
}

// Save creates the RecurringItem entities in the database.
func (_c *RecurringItemCreateBulk) Save(ctx context.Context) ([]*RecurringItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecurringItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecurringItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecurringItemCreateBulk) SaveX(ctx context.Context) []*RecurringItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
