// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringitem"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/transaction"
)

// RecurringInstance is the model entity for the RecurringInstance schema.
type RecurringInstance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DueDate holds the value of the "due_date" field.
	DueDate time.Time `json:"due_date,omitempty"`
	// EstimatedAmount holds the value of the "estimated_amount" field.
	EstimatedAmount float64 `json:"estimated_amount,omitempty"`
	// ActualAmount holds the value of the "actual_amount" field.
	ActualAmount *float64 `json:"actual_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status recurringinstance.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecurringInstanceQuery when eager-loading is set.
	Edges                    RecurringInstanceEdges `json:"edges"`
	recurring_item_instances *int
	selectValues             sql.SelectValues
}

// RecurringInstanceEdges holds the relations/edges for other nodes in the graph.
type RecurringInstanceEdges struct {
	// RecurringItem holds the value of the recurring_item edge.
	RecurringItem *RecurringItem `json:"recurring_item,omitempty"`
	// Transaction holds the value of the transaction edge.
	Transaction *Transaction `json:"transaction,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RecurringItemOrErr returns the RecurringItem value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecurringInstanceEdges) RecurringItemOrErr() (*RecurringItem, error) {
	if e.RecurringItem != nil {
		return e.RecurringItem, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: recurringitem.Label}
	}
	return nil, &NotLoadedError{edge: "recurring_item"}
}

// TransactionOrErr returns the Transaction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecurringInstanceEdges) TransactionOrErr() (*Transaction, error) {
	if e.Transaction != nil {
		return e.Transaction, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: transaction.Label}
	}
	return nil, &NotLoadedError{edge: "transaction"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecurringInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recurringinstance.FieldEstimatedAmount, recurringinstance.FieldActualAmount:
			values[i] = new(sql.NullFloat64)
		case recurringinstance.FieldID:
			values[i] = new(sql.NullInt64)
		case recurringinstance.FieldStatus:
			values[i] = new(sql.NullString)
		case recurringinstance.FieldDueDate:
			values[i] = new(sql.NullTime)
		case recurringinstance.ForeignKeys[0]: // recurring_item_instances
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecurringInstance fields.
func (_m *RecurringInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recurringinstance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case recurringinstance.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = value.Time
			}
		case recurringinstance.FieldEstimatedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_amount", values[i])
			} else if value.Valid {
				_m.EstimatedAmount = value.Float64
			}
		case recurringinstance.FieldActualAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_amount", values[i])
			} else if value.Valid {
				_m.ActualAmount = new(float64)
				*_m.ActualAmount = value.Float64
			}
		case recurringinstance.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = recurringinstance.Status(value.String)
			}
		case recurringinstance.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field recurring_item_instances", value)
			} else if value.Valid {
				_m.recurring_item_instances = new(int)
				*_m.recurring_item_instances = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecurringInstance.
// This includes values selected through modifiers, order, etc.
func (_m *RecurringInstance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecurringItem queries the "recurring_item" edge of the RecurringInstance entity.
func (_m *RecurringInstance) QueryRecurringItem() *RecurringItemQuery {
	return NewRecurringInstanceClient(_m.config).QueryRecurringItem(_m)
}

// QueryTransaction queries the "transaction" edge of the RecurringInstance entity.
func (_m *RecurringInstance) QueryTransaction() *TransactionQuery {
	return NewRecurringInstanceClient(_m.config).QueryTransaction(_m)
}

// Update returns a builder for updating this RecurringInstance.
// Note that you need to call RecurringInstance.Unwrap() before calling this method if this RecurringInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecurringInstance) Update() *RecurringInstanceUpdateOne {
	return NewRecurringInstanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecurringInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecurringInstance) Unwrap() *RecurringInstance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecurringInstance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecurringInstance) String() string {
	var builder strings.Builder
	builder.WriteString("RecurringInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("due_date=")
	builder.WriteString(_m.DueDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("estimated_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedAmount))
	builder.WriteString(", ")
	if v := _m.ActualAmount; v != nil {
		builder.WriteString("actual_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// RecurringInstances is a parsable slice of RecurringInstance.
type RecurringInstances []*RecurringInstance
