// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringitem"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/transaction"
)

// RecurringInstanceCreate is the builder for creating a RecurringInstance entity.
type RecurringInstanceCreate struct {
	config
	mutation *RecurringInstanceMutation
	hooks    []Hook
}

// SetDueDate sets the "due_date" field.
func (_c *RecurringInstanceCreate) SetDueDate(v time.Time) *RecurringInstanceCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetEstimatedAmount sets the "estimated_amount" field.
func (_c *RecurringInstanceCreate) SetEstimatedAmount(v float64) *RecurringInstanceCreate {
	_c.mutation.SetEstimatedAmount(v)
	return _c
}

// SetActualAmount sets the "actual_amount" field.
func (_c *RecurringInstanceCreate) SetActualAmount(v float64) *RecurringInstanceCreate {
	_c.mutation.SetActualAmount(v)
	return _c
}

// SetNillableActualAmount sets the "actual_amount" field if the given value is not nil.
func (_c *RecurringInstanceCreate) SetNillableActualAmount(v *float64) *RecurringInstanceCreate {
	if v != nil {
		_c.SetActualAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RecurringInstanceCreate) SetStatus(v recurringinstance.Status) *RecurringInstanceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RecurringInstanceCreate) SetNillableStatus(v *recurringinstance.Status) *RecurringInstanceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRecurringItemID sets the "recurring_item" edge to the RecurringItem entity by ID.
func (_c *RecurringInstanceCreate) SetRecurringItemID(id int) *RecurringInstanceCreate {
	_c.mutation.SetRecurringItemID(id)
	return _c
}

// SetRecurringItem sets the "recurring_item" edge to the RecurringItem entity.
func (_c *RecurringInstanceCreate) SetRecurringItem(v *RecurringItem) *RecurringInstanceCreate {
	return _c.SetRecurringItemID(v.ID)
}

// SetTransactionID sets the "transaction" edge to the Transaction entity by ID.
func (_c *RecurringInstanceCreate) SetTransactionID(id int) *RecurringInstanceCreate {
	_c.mutation.SetTransactionID(id)
	return _c
}

// SetNillableTransactionID sets the "transaction" edge to the Transaction entity by ID if the given value is not nil.
func (_c *RecurringInstanceCreate) SetNillableTransactionID(id *int) *RecurringInstanceCreate {
	if id != nil {
		_c = _c.SetTransactionID(*id)
	}
	return _c
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (_c *RecurringInstanceCreate) SetTransaction(v *Transaction) *RecurringInstanceCreate {
	return _c.SetTransactionID(v.ID)
}

// Mutation returns the RecurringInstanceMutation object of the builder.
func (_c *RecurringInstanceCreate) Mutation() *RecurringInstanceMutation {
	return _c.mutation
}

// Save creates the RecurringInstance in the database.
func (_c *RecurringInstanceCreate) Save(ctx context.Context) (*RecurringInstance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecurringInstanceCreate) SaveX(ctx context.Context) *RecurringInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringInstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringInstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecurringInstanceCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := recurringinstance.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecurringInstanceCreate) check() error {
	if _, ok := _c.mutation.DueDate(); !ok {
		return &ValidationError{Name: "due_date", err: errors.New(`ent: missing required field "RecurringInstance.due_date"`)}
	}
	if _, ok := _c.mutation.EstimatedAmount(); !ok {
		return &ValidationError{Name: "estimated_amount", err: errors.New(`ent: missing required field "RecurringInstance.estimated_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RecurringInstance.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := recurringinstance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RecurringInstance.status": %w`, err)}
		}
	}
	if len(_c.mutation.RecurringItemIDs()) == 0 {
		return &ValidationError{Name: "recurring_item", err: errors.New(`ent: missing required edge "RecurringInstance.recurring_item"`)}
	}
	return nil
}

func (_c *RecurringInstanceCreate) sqlSave(ctx context.Context) (*RecurringInstance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecurringInstanceCreate) createSpec() (*RecurringInstance, *sqlgraph.CreateSpec) {
	var (
		_node = &RecurringInstance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recurringinstance.Table, sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(recurringinstance.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if value, ok := _c.mutation.EstimatedAmount(); ok {
		_spec.SetField(recurringinstance.FieldEstimatedAmount, field.TypeFloat64, value)
		_node.EstimatedAmount = value
	}
	if value, ok := _c.mutation.ActualAmount(); ok {
		_spec.SetField(recurringinstance.FieldActualAmount, field.TypeFloat64, value)
		_node.ActualAmount = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(recurringinstance.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.RecurringItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringinstance.RecurringItemTable,
			Columns: []string{recurringinstance.RecurringItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.recurring_item_instances = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   recurringinstance.TransactionTable,
			Columns: []string{recurringinstance.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecurringInstanceCreateBulk is the builder for creating many RecurringInstance entities in bulk.
type RecurringInstanceCreateBulk struct {
	config
	err      error
	builders []*RecurringInstanceCreate
}

// Save creates the RecurringInstance entities in the database.
func (_c *RecurringInstanceCreateBulk) Save(ctx context.Context) ([]*RecurringInstance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecurringInstance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecurringInstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecurringInstanceCreateBulk) SaveX(ctx context.Context) []*RecurringInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringInstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringInstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
