// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
)

// RecurringInstanceDelete is the builder for deleting a RecurringInstance entity.
type RecurringInstanceDelete struct {
	config
	hooks    []Hook
	mutation *RecurringInstanceMutation
}

// Where appends a list predicates to the RecurringInstanceDelete builder.
func (_d *RecurringInstanceDelete) Where(ps ...predicate.RecurringInstance) *RecurringInstanceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RecurringInstanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecurringInstanceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RecurringInstanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recurringinstance.Table, sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RecurringInstanceDeleteOne is the builder for deleting a single RecurringInstance entity.
type RecurringInstanceDeleteOne struct {
	_d *RecurringInstanceDelete
}

// Where appends a list predicates to the RecurringInstanceDelete builder.
func (_d *RecurringInstanceDeleteOne) Where(ps ...predicate.RecurringInstance) *RecurringInstanceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RecurringInstanceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recurringinstance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecurringInstanceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
