// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/category"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringitem"
)

// RecurringItem is the model entity for the RecurringItem schema.
type RecurringItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind recurringitem.Kind `json:"kind,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Frequency holds the value of the "frequency" field.
	Frequency recurringitem.Frequency `json:"frequency,omitempty"`
	// EstimatedAmount holds the value of the "estimated_amount" field.
	EstimatedAmount float64 `json:"estimated_amount,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecurringItemQuery when eager-loading is set.
	Edges                    RecurringItemEdges `json:"edges"`
	account_recurring_items  *int
	category_recurring_items *int
	selectValues             sql.SelectValues
}

// RecurringItemEdges holds the relations/edges for other nodes in the graph.
type RecurringItemEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// Instances holds the value of the instances edge.
	Instances []*RecurringInstance `json:"instances,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecurringItemEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecurringItemEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// InstancesOrErr returns the Instances value or an error if the edge
// was not loaded in eager-loading.
func (e RecurringItemEdges) InstancesOrErr() ([]*RecurringInstance, error) {
	if e.loadedTypes[2] {
		return e.Instances, nil
	}
	return nil, &NotLoadedError{edge: "instances"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecurringItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recurringitem.FieldActive:
			values[i] = new(sql.NullBool)
		case recurringitem.FieldEstimatedAmount:
			values[i] = new(sql.NullFloat64)
		case recurringitem.FieldID:
			values[i] = new(sql.NullInt64)
		case recurringitem.FieldKind, recurringitem.FieldName, recurringitem.FieldFrequency:
			values[i] = new(sql.NullString)
		case recurringitem.FieldStartDate:
			values[i] = new(sql.NullTime)
		case recurringitem.ForeignKeys[0]: // account_recurring_items
			values[i] = new(sql.NullInt64)
		case recurringitem.ForeignKeys[1]: // category_recurring_items
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecurringItem fields.
func (_m *RecurringItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recurringitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case recurringitem.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = recurringitem.Kind(value.String)
			}
		case recurringitem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case recurringitem.FieldFrequency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frequency", values[i])
			} else if value.Valid {
				_m.Frequency = recurringitem.Frequency(value.String)
			}
		case recurringitem.FieldEstimatedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_amount", values[i])
			} else if value.Valid {
				_m.EstimatedAmount = value.Float64
			}
		case recurringitem.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case recurringitem.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case recurringitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field account_recurring_items", value)
			} else if value.Valid {
				_m.account_recurring_items = new(int)
				*_m.account_recurring_items = int(value.Int64)
			}
		case recurringitem.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field category_recurring_items", value)
			} else if value.Valid {
				_m.category_recurring_items = new(int)
				*_m.category_recurring_items = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecurringItem.
// This includes values selected through modifiers, order, etc.
func (_m *RecurringItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the RecurringItem entity.
func (_m *RecurringItem) QueryAccount() *AccountQuery {
	return NewRecurringItemClient(_m.config).QueryAccount(_m)
}

// QueryCategory queries the "category" edge of the RecurringItem entity.
func (_m *RecurringItem) QueryCategory() *CategoryQuery {
	return NewRecurringItemClient(_m.config).QueryCategory(_m)
}

// QueryInstances queries the "instances" edge of the RecurringItem entity.
func (_m *RecurringItem) QueryInstances() *RecurringInstanceQuery {
	return NewRecurringItemClient(_m.config).QueryInstances(_m)
}

// Update returns a builder for updating this RecurringItem.
// Note that you need to call RecurringItem.Unwrap() before calling this method if this RecurringItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecurringItem) Update() *RecurringItemUpdateOne {
	return NewRecurringItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecurringItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecurringItem) Unwrap() *RecurringItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecurringItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecurringItem) String() string {
	var builder strings.Builder
	builder.WriteString("RecurringItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("frequency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Frequency))
	builder.WriteString(", ")
	builder.WriteString("estimated_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedAmount))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteByte(')')
	return builder.String()
}

// RecurringItems is a parsable slice of RecurringItem.
type RecurringItems []*RecurringItem
