// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/category"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringitem"
)

// RecurringItemUpdate is the builder for updating RecurringItem entities.
type RecurringItemUpdate struct {
	config
	hooks    []Hook
	mutation *RecurringItemMutation
}

// Where appends a list predicates to the RecurringItemUpdate builder.
func (_u *RecurringItemUpdate) Where(ps ...predicate.RecurringItem) *RecurringItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *RecurringItemUpdate) SetKind(v recurringitem.Kind) *RecurringItemUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableKind(v *recurringitem.Kind) *RecurringItemUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RecurringItemUpdate) SetName(v string) *RecurringItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableName(v *string) *RecurringItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *RecurringItemUpdate) SetFrequency(v recurringitem.Frequency) *RecurringItemUpdate {
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableFrequency(v *recurringitem.Frequency) *RecurringItemUpdate {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// SetEstimatedAmount sets the "estimated_amount" field.
func (_u *RecurringItemUpdate) SetEstimatedAmount(v float64) *RecurringItemUpdate {
	_u.mutation.ResetEstimatedAmount()
	_u.mutation.SetEstimatedAmount(v)
	return _u
}

// SetNillableEstimatedAmount sets the "estimated_amount" field if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableEstimatedAmount(v *float64) *RecurringItemUpdate {
	if v != nil {
		_u.SetEstimatedAmount(*v)
	}
	return _u
}

// AddEstimatedAmount adds value to the "estimated_amount" field.
func (_u *RecurringItemUpdate) AddEstimatedAmount(v float64) *RecurringItemUpdate {
	_u.mutation.AddEstimatedAmount(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *RecurringItemUpdate) SetStartDate(v time.Time) *RecurringItemUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableStartDate(v *time.Time) *RecurringItemUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *RecurringItemUpdate) SetActive(v bool) *RecurringItemUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableActive(v *bool) *RecurringItemUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *RecurringItemUpdate) SetEndDate(v time.Time) *RecurringItemUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableEndDate(v *time.Time) *RecurringItemUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *RecurringItemUpdate) ClearEndDate() *RecurringItemUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetPreTax sets the "pre_tax" field.
func (_u *RecurringItemUpdate) SetPreTax(v bool) *RecurringItemUpdate {
	_u.mutation.SetPreTax(v)
	return _u
}

// SetNillablePreTax sets the "pre_tax" field if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillablePreTax(v *bool) *RecurringItemUpdate {
	if v != nil {
		_u.SetPreTax(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *RecurringItemUpdate) SetAccountID(id int) *RecurringItemUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableAccountID(id *int) *RecurringItemUpdate {
	if id != nil {
		_u = _u.SetAccountID(*id)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *RecurringItemUpdate) SetAccount(v *Account) *RecurringItemUpdate {
	return _u.SetAccountID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *RecurringItemUpdate) SetCategoryID(id int) *RecurringItemUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *RecurringItemUpdate) SetNillableCategoryID(id *int) *RecurringItemUpdate {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *RecurringItemUpdate) SetCategory(v *Category) *RecurringItemUpdate {
	return _u.SetCategoryID(v.ID)
}

// AddInstanceIDs adds the "instances" edge to the RecurringInstance entity by IDs.
func (_u *RecurringItemUpdate) AddInstanceIDs(ids ...int) *RecurringItemUpdate {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the RecurringInstance entity.
func (_u *RecurringItemUpdate) AddInstances(v ...*RecurringInstance) *RecurringItemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// Mutation returns the RecurringItemMutation object of the builder.
func (_u *RecurringItemUpdate) Mutation() *RecurringItemMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *RecurringItemUpdate) ClearAccount() *RecurringItemUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *RecurringItemUpdate) ClearCategory() *RecurringItemUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// ClearInstances clears all "instances" edges to the RecurringInstance entity.
func (_u *RecurringItemUpdate) ClearInstances() *RecurringItemUpdate {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to RecurringInstance entities by IDs.
func (_u *RecurringItemUpdate) RemoveInstanceIDs(ids ...int) *RecurringItemUpdate {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to RecurringInstance entities.
func (_u *RecurringItemUpdate) RemoveInstances(v ...*RecurringInstance) *RecurringItemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecurringItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecurringItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringItemUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := recurringitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := recurringitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Frequency(); ok {
		if err := recurringitem.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.frequency": %w`, err)}
		}
	}
	return nil
}

func (_u *RecurringItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringitem.Table, recurringitem.Columns, sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(recurringitem.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(recurringitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(recurringitem.FieldFrequency, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EstimatedAmount(); ok {
		_spec.SetField(recurringitem.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedAmount(); ok {
		_spec.AddField(recurringitem.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(recurringitem.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(recurringitem.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(recurringitem.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(recurringitem.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.PreTax(); ok {
		_spec.SetField(recurringitem.FieldPreTax, field.TypeBool, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.AccountTable,
			Columns: []string{recurringitem.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.AccountTable,
			Columns: []string{recurringitem.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.CategoryTable,
			Columns: []string{recurringitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.CategoryTable,
			Columns: []string{recurringitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recurringitem.InstancesTable,
			Columns: []string{recurringitem.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recurringitem.InstancesTable,
			Columns: []string{recurringitem.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recurringitem.InstancesTable,
			Columns: []string{recurringitem.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecurringItemUpdateOne is the builder for updating a single RecurringItem entity.
type RecurringItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecurringItemMutation
}

// SetKind sets the "kind" field.
func (_u *RecurringItemUpdateOne) SetKind(v recurringitem.Kind) *RecurringItemUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableKind(v *recurringitem.Kind) *RecurringItemUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RecurringItemUpdateOne) SetName(v string) *RecurringItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableName(v *string) *RecurringItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *RecurringItemUpdateOne) SetFrequency(v recurringitem.Frequency) *RecurringItemUpdateOne {
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableFrequency(v *recurringitem.Frequency) *RecurringItemUpdateOne {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// SetEstimatedAmount sets the "estimated_amount" field.
func (_u *RecurringItemUpdateOne) SetEstimatedAmount(v float64) *RecurringItemUpdateOne {
	_u.mutation.ResetEstimatedAmount()
	_u.mutation.SetEstimatedAmount(v)
	return _u
}

// SetNillableEstimatedAmount sets the "estimated_amount" field if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableEstimatedAmount(v *float64) *RecurringItemUpdateOne {
	if v != nil {
		_u.SetEstimatedAmount(*v)
	}
	return _u
}

// AddEstimatedAmount adds value to the "estimated_amount" field.
func (_u *RecurringItemUpdateOne) AddEstimatedAmount(v float64) *RecurringItemUpdateOne {
	_u.mutation.AddEstimatedAmount(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *RecurringItemUpdateOne) SetStartDate(v time.Time) *RecurringItemUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableStartDate(v *time.Time) *RecurringItemUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *RecurringItemUpdateOne) SetActive(v bool) *RecurringItemUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableActive(v *bool) *RecurringItemUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *RecurringItemUpdateOne) SetEndDate(v time.Time) *RecurringItemUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableEndDate(v *time.Time) *RecurringItemUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *RecurringItemUpdateOne) ClearEndDate() *RecurringItemUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetPreTax sets the "pre_tax" field.
func (_u *RecurringItemUpdateOne) SetPreTax(v bool) *RecurringItemUpdateOne {
	_u.mutation.SetPreTax(v)
	return _u
}

// SetNillablePreTax sets the "pre_tax" field if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillablePreTax(v *bool) *RecurringItemUpdateOne {
	if v != nil {
		_u.SetPreTax(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *RecurringItemUpdateOne) SetAccountID(id int) *RecurringItemUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableAccountID(id *int) *RecurringItemUpdateOne {
	if id != nil {
		_u = _u.SetAccountID(*id)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *RecurringItemUpdateOne) SetAccount(v *Account) *RecurringItemUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *RecurringItemUpdateOne) SetCategoryID(id int) *RecurringItemUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *RecurringItemUpdateOne) SetNillableCategoryID(id *int) *RecurringItemUpdateOne {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *RecurringItemUpdateOne) SetCategory(v *Category) *RecurringItemUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// AddInstanceIDs adds the "instances" edge to the RecurringInstance entity by IDs.
func (_u *RecurringItemUpdateOne) AddInstanceIDs(ids ...int) *RecurringItemUpdateOne {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the RecurringInstance entity.
func (_u *RecurringItemUpdateOne) AddInstances(v ...*RecurringInstance) *RecurringItemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// Mutation returns the RecurringItemMutation object of the builder.
func (_u *RecurringItemUpdateOne) Mutation() *RecurringItemMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *RecurringItemUpdateOne) ClearAccount() *RecurringItemUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *RecurringItemUpdateOne) ClearCategory() *RecurringItemUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// ClearInstances clears all "instances" edges to the RecurringInstance entity.
func (_u *RecurringItemUpdateOne) ClearInstances() *RecurringItemUpdateOne {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to RecurringInstance entities by IDs.
func (_u *RecurringItemUpdateOne) RemoveInstanceIDs(ids ...int) *RecurringItemUpdateOne {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to RecurringInstance entities.
func (_u *RecurringItemUpdateOne) RemoveInstances(v ...*RecurringInstance) *RecurringItemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// Where appends a list predicates to the RecurringItemUpdate builder.
func (_u *RecurringItemUpdateOne) Where(ps ...predicate.RecurringItem) *RecurringItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecurringItemUpdateOne) Select(field string, fields ...string) *RecurringItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RecurringItem entity.
func (_u *RecurringItemUpdateOne) Save(ctx context.Context) (*RecurringItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringItemUpdateOne) SaveX(ctx context.Context) *RecurringItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecurringItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringItemUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := recurringitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := recurringitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Frequency(); ok {
		if err := recurringitem.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringItem.frequency": %w`, err)}
		}
	}
	return nil
}

func (_u *RecurringItemUpdateOne) sqlSave(ctx context.Context) (_node *RecurringItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringitem.Table, recurringitem.Columns, sqlgraph.NewFieldSpec(recurringitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecurringItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringitem.FieldID)
		for _, f := range fields {
			if !recurringitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recurringitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(recurringitem.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(recurringitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(recurringitem.FieldFrequency, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EstimatedAmount(); ok {
		_spec.SetField(recurringitem.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedAmount(); ok {
		_spec.AddField(recurringitem.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(recurringitem.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(recurringitem.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(recurringitem.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(recurringitem.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.PreTax(); ok {
		_spec.SetField(recurringitem.FieldPreTax, field.TypeBool, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.AccountTable,
			Columns: []string{recurringitem.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.AccountTable,
			Columns: []string{recurringitem.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.CategoryTable,
			Columns: []string{recurringitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringitem.CategoryTable,
			Columns: []string{recurringitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recurringitem.InstancesTable,
			Columns: []string{recurringitem.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recurringitem.InstancesTable,
			Columns: []string{recurringitem.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recurringitem.InstancesTable,
			Columns: []string{recurringitem.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RecurringItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
