// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/category"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringitem"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/schema"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/transaction"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[6].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	accountsnapshotFields := schema.AccountSnapshot{}.Fields()
	_ = accountsnapshotFields
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	recurringinstanceFields := schema.RecurringInstance{}.Fields()
	_ = recurringinstanceFields
	recurringitemFields := schema.RecurringItem{}.Fields()
	_ = recurringitemFields
	// recurringitemDescName is the schema descriptor for name field.
	recurringitemDescName := recurringitemFields[1].Descriptor()
	// recurringitem.NameValidator is a validator for the "name" field. It is called by the builders before save.
	recurringitem.NameValidator = recurringitemDescName.Validators[0].(func(string) error)
	// recurringitemDescActive is the schema descriptor for active field.
	recurringitemDescActive := recurringitemFields[5].Descriptor()
	// recurringitem.DefaultActive holds the default value on creation for the active field.
	recurringitem.DefaultActive = recurringitemDescActive.Default.(bool)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[7].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
}
