// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/category"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/transaction"
)

// TransactionCreate is the builder for creating a Transaction entity.
type TransactionCreate struct {
	config
	mutation *TransactionMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (_c *TransactionCreate) SetAmount(v float64) *TransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TransactionCreate) SetDescription(v string) *TransactionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableDescription(v *string) *TransactionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPostedDate sets the "posted_date" field.
func (_c *TransactionCreate) SetPostedDate(v time.Time) *TransactionCreate {
	_c.mutation.SetPostedDate(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *TransactionCreate) SetSource(v transaction.Source) *TransactionCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableSource(v *transaction.Source) *TransactionCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TransactionCreate) SetStatus(v transaction.Status) *TransactionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableStatus(v *transaction.Status) *TransactionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *TransactionCreate) SetExternalID(v string) *TransactionCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableExternalID(v *string) *TransactionCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetClassification sets the "classification" field.
func (_c *TransactionCreate) SetClassification(v transaction.Classification) *TransactionCreate {
	_c.mutation.SetClassification(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TransactionCreate) SetCreatedAt(v time.Time) *TransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableCreatedAt(v *time.Time) *TransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *TransactionCreate) SetAccountID(id int) *TransactionCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *TransactionCreate) SetAccount(v *Account) *TransactionCreate {
	return _c.SetAccountID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_c *TransactionCreate) SetCategoryID(id int) *TransactionCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_c *TransactionCreate) SetNillableCategoryID(id *int) *TransactionCreate {
	if id != nil {
		_c = _c.SetCategoryID(*id)
	}
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *TransactionCreate) SetCategory(v *Category) *TransactionCreate {
	return _c.SetCategoryID(v.ID)
}

// SetRecurringInstanceID sets the "recurring_instance" edge to the RecurringInstance entity by ID.
func (_c *TransactionCreate) SetRecurringInstanceID(id int) *TransactionCreate {
	_c.mutation.SetRecurringInstanceID(id)
	return _c
}

// SetNillableRecurringInstanceID sets the "recurring_instance" edge to the RecurringInstance entity by ID if the given value is not nil.
func (_c *TransactionCreate) SetNillableRecurringInstanceID(id *int) *TransactionCreate {
	if id != nil {
		_c = _c.SetRecurringInstanceID(*id)
	}
	return _c
}

// SetRecurringInstance sets the "recurring_instance" edge to the RecurringInstance entity.
func (_c *TransactionCreate) SetRecurringInstance(v *RecurringInstance) *TransactionCreate {
	return _c.SetRecurringInstanceID(v.ID)
}

// SetTransferPairID sets the "transfer_pair" edge to the Transaction entity by ID.
func (_c *TransactionCreate) SetTransferPairID(id int) *TransactionCreate {
	_c.mutation.SetTransferPairID(id)
	return _c
}

// SetNillableTransferPairID sets the "transfer_pair" edge to the Transaction entity by ID if the given value is not nil.
func (_c *TransactionCreate) SetNillableTransferPairID(id *int) *TransactionCreate {
	if id != nil {
		_c = _c.SetTransferPairID(*id)
	}
	return _c
}

// SetTransferPair sets the "transfer_pair" edge to the Transaction entity.
func (_c *TransactionCreate) SetTransferPair(v *Transaction) *TransactionCreate {
	return _c.SetTransferPairID(v.ID)
}

// SetTransferPairOfID sets the "transfer_pair_of" edge to the Transaction entity by ID.
func (_c *TransactionCreate) SetTransferPairOfID(id int) *TransactionCreate {
	_c.mutation.SetTransferPairOfID(id)
	return _c
}

// SetNillableTransferPairOfID sets the "transfer_pair_of" edge to the Transaction entity by ID if the given value is not nil.
func (_c *TransactionCreate) SetNillableTransferPairOfID(id *int) *TransactionCreate {
	if id != nil {
		_c = _c.SetTransferPairOfID(*id)
	}
	return _c
}

// SetTransferPairOf sets the "transfer_pair_of" edge to the Transaction entity.
func (_c *TransactionCreate) SetTransferPairOf(v *Transaction) *TransactionCreate {
	return _c.SetTransferPairOfID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_c *TransactionCreate) Mutation() *TransactionMutation {
	return _c.mutation
}

// Save creates the Transaction in the database.
func (_c *TransactionCreate) Save(ctx context.Context) (*Transaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransactionCreate) SaveX(ctx context.Context) *Transaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransactionCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := transaction.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := transaction.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := transaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransactionCreate) check() error {
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Transaction.amount"`)}
	}
	if _, ok := _c.mutation.PostedDate(); !ok {
		return &ValidationError{Name: "posted_date", err: errors.New(`ent: missing required field "Transaction.posted_date"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Transaction.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := transaction.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Transaction.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Transaction.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := transaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Transaction.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Classification(); !ok {
		return &ValidationError{Name: "classification", err: errors.New(`ent: missing required field "Transaction.classification"`)}
	}
	if v, ok := _c.mutation.Classification(); ok {
		if err := transaction.ClassificationValidator(v); err != nil {
			return &ValidationError{Name: "classification", err: fmt.Errorf(`ent: validator failed for field "Transaction.classification": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Transaction.created_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "Transaction.account"`)}
	}
	return nil
}

func (_c *TransactionCreate) sqlSave(ctx context.Context) (*Transaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransactionCreate) createSpec() (*Transaction, *sqlgraph.CreateSpec) {
	var (
		_node = &Transaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transaction.Table, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PostedDate(); ok {
		_spec.SetField(transaction.FieldPostedDate, field.TypeTime, value)
		_node.PostedDate = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(transaction.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(transaction.FieldExternalID, field.TypeString, value)
		_node.ExternalID = &value
	}
	if value, ok := _c.mutation.Classification(); ok {
		_spec.SetField(transaction.FieldClassification, field.TypeEnum, value)
		_node.Classification = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(transaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_transactions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.CategoryTable,
			Columns: []string{transaction.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.category_transactions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecurringInstanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.RecurringInstanceTable,
			Columns: []string{transaction.RecurringInstanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.recurring_instance_transaction = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransferPairIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   transaction.TransferPairTable,
			Columns: []string{transaction.TransferPairColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.transaction_transfer_pair = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransferPairOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.TransferPairOfTable,
			Columns: []string{transaction.TransferPairOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.transaction_transfer_pair = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TransactionCreateBulk is the builder for creating many Transaction entities in bulk.
type TransactionCreateBulk struct {
	config
	err      error
	builders []*TransactionCreate
}

// Save creates the Transaction entities in the database.
func (_c *TransactionCreateBulk) Save(ctx context.Context) ([]*Transaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Transaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransactionCreateBulk) SaveX(ctx context.Context) []*Transaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
