// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/category"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/transaction"
)

// Transaction is the model entity for the Transaction schema.
type Transaction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PostedDate holds the value of the "posted_date" field.
	PostedDate time.Time `json:"posted_date,omitempty"`
	// Source holds the value of the "source" field.
	Source transaction.Source `json:"source,omitempty"`
	// Status holds the value of the "status" field.
	Status transaction.Status `json:"status,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID *string `json:"external_id,omitempty"`
	// Classification holds the value of the "classification" field.
	Classification transaction.Classification `json:"classification,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransactionQuery when eager-loading is set.
	Edges                          TransactionEdges `json:"edges"`
	account_transactions           *int
	category_transactions          *int
	recurring_instance_transaction *int
	transaction_transfer_pair      *int
	selectValues                   sql.SelectValues
}

// TransactionEdges holds the relations/edges for other nodes in the graph.
type TransactionEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// RecurringInstance holds the value of the recurring_instance edge.
	RecurringInstance *RecurringInstance `json:"recurring_instance,omitempty"`
	// TransferPair holds the value of the transfer_pair edge.
	TransferPair *Transaction `json:"transfer_pair,omitempty"`
	// TransferPairOf holds the value of the transfer_pair_of edge.
	TransferPairOf *Transaction `json:"transfer_pair_of,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// RecurringInstanceOrErr returns the RecurringInstance value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) RecurringInstanceOrErr() (*RecurringInstance, error) {
	if e.RecurringInstance != nil {
		return e.RecurringInstance, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: recurringinstance.Label}
	}
	return nil, &NotLoadedError{edge: "recurring_instance"}
}

// TransferPairOrErr returns the TransferPair value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) TransferPairOrErr() (*Transaction, error) {
	if e.TransferPair != nil {
		return e.TransferPair, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: transaction.Label}
	}
	return nil, &NotLoadedError{edge: "transfer_pair"}
}

// TransferPairOfOrErr returns the TransferPairOf value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) TransferPairOfOrErr() (*Transaction, error) {
	if e.TransferPairOf != nil {
		return e.TransferPairOf, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: transaction.Label}
	}
	return nil, &NotLoadedError{edge: "transfer_pair_of"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Transaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transaction.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case transaction.FieldID:
			values[i] = new(sql.NullInt64)
		case transaction.FieldDescription, transaction.FieldSource, transaction.FieldStatus, transaction.FieldExternalID, transaction.FieldClassification:
			values[i] = new(sql.NullString)
		case transaction.FieldPostedDate, transaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case transaction.ForeignKeys[0]: // account_transactions
			values[i] = new(sql.NullInt64)
		case transaction.ForeignKeys[1]: // category_transactions
			values[i] = new(sql.NullInt64)
		case transaction.ForeignKeys[2]: // recurring_instance_transaction
			values[i] = new(sql.NullInt64)
		case transaction.ForeignKeys[3]: // transaction_transfer_pair
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Transaction fields.
func (_m *Transaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case transaction.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case transaction.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case transaction.FieldPostedDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field posted_date", values[i])
			} else if value.Valid {
				_m.PostedDate = value.Time
			}
		case transaction.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = transaction.Source(value.String)
			}
		case transaction.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = transaction.Status(value.String)
			}
		case transaction.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = new(string)
				*_m.ExternalID = value.String
			}
		case transaction.FieldClassification:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classification", values[i])
			} else if value.Valid {
				_m.Classification = transaction.Classification(value.String)
			}
		case transaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case transaction.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field account_transactions", value)
			} else if value.Valid {
				_m.account_transactions = new(int)
				*_m.account_transactions = int(value.Int64)
			}
		case transaction.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field category_transactions", value)
			} else if value.Valid {
				_m.category_transactions = new(int)
				*_m.category_transactions = int(value.Int64)
			}
		case transaction.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field recurring_instance_transaction", value)
			} else if value.Valid {
				_m.recurring_instance_transaction = new(int)
				*_m.recurring_instance_transaction = int(value.Int64)
			}
		case transaction.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field transaction_transfer_pair", value)
			} else if value.Valid {
				_m.transaction_transfer_pair = new(int)
				*_m.transaction_transfer_pair = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Transaction.
// This includes values selected through modifiers, order, etc.
func (_m *Transaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the Transaction entity.
func (_m *Transaction) QueryAccount() *AccountQuery {
	return NewTransactionClient(_m.config).QueryAccount(_m)
}

// QueryCategory queries the "category" edge of the Transaction entity.
func (_m *Transaction) QueryCategory() *CategoryQuery {
	return NewTransactionClient(_m.config).QueryCategory(_m)
}

// QueryRecurringInstance queries the "recurring_instance" edge of the Transaction entity.
func (_m *Transaction) QueryRecurringInstance() *RecurringInstanceQuery {
	return NewTransactionClient(_m.config).QueryRecurringInstance(_m)
}

// QueryTransferPair queries the "transfer_pair" edge of the Transaction entity.
func (_m *Transaction) QueryTransferPair() *TransactionQuery {
	return NewTransactionClient(_m.config).QueryTransferPair(_m)
}

// QueryTransferPairOf queries the "transfer_pair_of" edge of the Transaction entity.
func (_m *Transaction) QueryTransferPairOf() *TransactionQuery {
	return NewTransactionClient(_m.config).QueryTransferPairOf(_m)
}

// Update returns a builder for updating this Transaction.
// Note that you need to call Transaction.Unwrap() before calling this method if this Transaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Transaction) Update() *TransactionUpdateOne {
	return NewTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Transaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Transaction) Unwrap() *Transaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Transaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Transaction) String() string {
	var builder strings.Builder
	builder.WriteString("Transaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("posted_date=")
	builder.WriteString(_m.PostedDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ExternalID; v != nil {
		builder.WriteString("external_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("classification=")
	builder.WriteString(fmt.Sprintf("%v", _m.Classification))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Transactions is a parsable slice of Transaction.
type Transactions []*Transaction
