// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/account"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/category"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/recurringinstance"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/transaction"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdate) SetAmount(v float64) *TransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableAmount(v *float64) *TransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdate) AddAmount(v float64) *TransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdate) SetDescription(v string) *TransactionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableDescription(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TransactionUpdate) ClearDescription() *TransactionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPostedDate sets the "posted_date" field.
func (_u *TransactionUpdate) SetPostedDate(v time.Time) *TransactionUpdate {
	_u.mutation.SetPostedDate(v)
	return _u
}

// SetNillablePostedDate sets the "posted_date" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillablePostedDate(v *time.Time) *TransactionUpdate {
	if v != nil {
		_u.SetPostedDate(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *TransactionUpdate) SetSource(v transaction.Source) *TransactionUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableSource(v *transaction.Source) *TransactionUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransactionUpdate) SetStatus(v transaction.Status) *TransactionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableStatus(v *transaction.Status) *TransactionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *TransactionUpdate) SetExternalID(v string) *TransactionUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableExternalID(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *TransactionUpdate) ClearExternalID() *TransactionUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetClassification sets the "classification" field.
func (_u *TransactionUpdate) SetClassification(v transaction.Classification) *TransactionUpdate {
	_u.mutation.SetClassification(v)
	return _u
}

// SetNillableClassification sets the "classification" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableClassification(v *transaction.Classification) *TransactionUpdate {
	if v != nil {
		_u.SetClassification(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *TransactionUpdate) SetAccountID(id int) *TransactionUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *TransactionUpdate) SetAccount(v *Account) *TransactionUpdate {
	return _u.SetAccountID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *TransactionUpdate) SetCategoryID(id int) *TransactionUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCategoryID(id *int) *TransactionUpdate {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *TransactionUpdate) SetCategory(v *Category) *TransactionUpdate {
	return _u.SetCategoryID(v.ID)
}

// SetRecurringInstanceID sets the "recurring_instance" edge to the RecurringInstance entity by ID.
func (_u *TransactionUpdate) SetRecurringInstanceID(id int) *TransactionUpdate {
	_u.mutation.SetRecurringInstanceID(id)
	return _u
}

// SetNillableRecurringInstanceID sets the "recurring_instance" edge to the RecurringInstance entity by ID if the given value is not nil.
func (_u *TransactionUpdate) SetNillableRecurringInstanceID(id *int) *TransactionUpdate {
	if id != nil {
		_u = _u.SetRecurringInstanceID(*id)
	}
	return _u
}

// SetRecurringInstance sets the "recurring_instance" edge to the RecurringInstance entity.
func (_u *TransactionUpdate) SetRecurringInstance(v *RecurringInstance) *TransactionUpdate {
	return _u.SetRecurringInstanceID(v.ID)
}

// SetTransferPairID sets the "transfer_pair" edge to the Transaction entity by ID.
func (_u *TransactionUpdate) SetTransferPairID(id int) *TransactionUpdate {
	_u.mutation.SetTransferPairID(id)
	return _u
}

// SetNillableTransferPairID sets the "transfer_pair" edge to the Transaction entity by ID if the given value is not nil.
func (_u *TransactionUpdate) SetNillableTransferPairID(id *int) *TransactionUpdate {
	if id != nil {
		_u = _u.SetTransferPairID(*id)
	}
	return _u
}

// SetTransferPair sets the "transfer_pair" edge to the Transaction entity.
func (_u *TransactionUpdate) SetTransferPair(v *Transaction) *TransactionUpdate {
	return _u.SetTransferPairID(v.ID)
}

// SetTransferPairOfID sets the "transfer_pair_of" edge to the Transaction entity by ID.
func (_u *TransactionUpdate) SetTransferPairOfID(id int) *TransactionUpdate {
	_u.mutation.SetTransferPairOfID(id)
	return _u
}

// SetNillableTransferPairOfID sets the "transfer_pair_of" edge to the Transaction entity by ID if the given value is not nil.
func (_u *TransactionUpdate) SetNillableTransferPairOfID(id *int) *TransactionUpdate {
	if id != nil {
		_u = _u.SetTransferPairOfID(*id)
	}
	return _u
}

// SetTransferPairOf sets the "transfer_pair_of" edge to the Transaction entity.
func (_u *TransactionUpdate) SetTransferPairOf(v *Transaction) *TransactionUpdate {
	return _u.SetTransferPairOfID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdate) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *TransactionUpdate) ClearAccount() *TransactionUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *TransactionUpdate) ClearCategory() *TransactionUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// ClearRecurringInstance clears the "recurring_instance" edge to the RecurringInstance entity.
func (_u *TransactionUpdate) ClearRecurringInstance() *TransactionUpdate {
	_u.mutation.ClearRecurringInstance()
	return _u
}

// ClearTransferPair clears the "transfer_pair" edge to the Transaction entity.
func (_u *TransactionUpdate) ClearTransferPair() *TransactionUpdate {
	_u.mutation.ClearTransferPair()
	return _u
}

// ClearTransferPairOf clears the "transfer_pair_of" edge to the Transaction entity.
func (_u *TransactionUpdate) ClearTransferPairOf() *TransactionUpdate {
	_u.mutation.ClearTransferPairOf()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := transaction.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Transaction.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := transaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Transaction.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Classification(); ok {
		if err := transaction.ClassificationValidator(v); err != nil {
			return &ValidationError{Name: "classification", err: fmt.Errorf(`ent: validator failed for field "Transaction.classification": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Transaction.account"`)
	}
	return nil
}

func (_u *TransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(transaction.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PostedDate(); ok {
		_spec.SetField(transaction.FieldPostedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(transaction.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(transaction.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(transaction.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.Classification(); ok {
		_spec.SetField(transaction.FieldClassification, field.TypeEnum, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.CategoryTable,
			Columns: []string{transaction.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.CategoryTable,
			Columns: []string{transaction.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecurringInstanceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.RecurringInstanceTable,
			Columns: []string{transaction.RecurringInstanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringInstanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.RecurringInstanceTable,
			Columns: []string{transaction.RecurringInstanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransferPairCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   transaction.TransferPairTable,
			Columns: []string{transaction.TransferPairColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferPairIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   transaction.TransferPairTable,
			Columns: []string{transaction.TransferPairColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransferPairOfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.TransferPairOfTable,
			Columns: []string{transaction.TransferPairOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferPairOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.TransferPairOfTable,
			Columns: []string{transaction.TransferPairOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdateOne) SetAmount(v float64) *TransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableAmount(v *float64) *TransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdateOne) AddAmount(v float64) *TransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdateOne) SetDescription(v string) *TransactionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableDescription(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TransactionUpdateOne) ClearDescription() *TransactionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPostedDate sets the "posted_date" field.
func (_u *TransactionUpdateOne) SetPostedDate(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetPostedDate(v)
	return _u
}

// SetNillablePostedDate sets the "posted_date" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillablePostedDate(v *time.Time) *TransactionUpdateOne {
	if v != nil {
		_u.SetPostedDate(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *TransactionUpdateOne) SetSource(v transaction.Source) *TransactionUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableSource(v *transaction.Source) *TransactionUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransactionUpdateOne) SetStatus(v transaction.Status) *TransactionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableStatus(v *transaction.Status) *TransactionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *TransactionUpdateOne) SetExternalID(v string) *TransactionUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableExternalID(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *TransactionUpdateOne) ClearExternalID() *TransactionUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetClassification sets the "classification" field.
func (_u *TransactionUpdateOne) SetClassification(v transaction.Classification) *TransactionUpdateOne {
	_u.mutation.SetClassification(v)
	return _u
}

// SetNillableClassification sets the "classification" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableClassification(v *transaction.Classification) *TransactionUpdateOne {
	if v != nil {
		_u.SetClassification(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *TransactionUpdateOne) SetAccountID(id int) *TransactionUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *TransactionUpdateOne) SetAccount(v *Account) *TransactionUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *TransactionUpdateOne) SetCategoryID(id int) *TransactionUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCategoryID(id *int) *TransactionUpdateOne {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *TransactionUpdateOne) SetCategory(v *Category) *TransactionUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// SetRecurringInstanceID sets the "recurring_instance" edge to the RecurringInstance entity by ID.
func (_u *TransactionUpdateOne) SetRecurringInstanceID(id int) *TransactionUpdateOne {
	_u.mutation.SetRecurringInstanceID(id)
	return _u
}

// SetNillableRecurringInstanceID sets the "recurring_instance" edge to the RecurringInstance entity by ID if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableRecurringInstanceID(id *int) *TransactionUpdateOne {
	if id != nil {
		_u = _u.SetRecurringInstanceID(*id)
	}
	return _u
}

// SetRecurringInstance sets the "recurring_instance" edge to the RecurringInstance entity.
func (_u *TransactionUpdateOne) SetRecurringInstance(v *RecurringInstance) *TransactionUpdateOne {
	return _u.SetRecurringInstanceID(v.ID)
}

// SetTransferPairID sets the "transfer_pair" edge to the Transaction entity by ID.
func (_u *TransactionUpdateOne) SetTransferPairID(id int) *TransactionUpdateOne {
	_u.mutation.SetTransferPairID(id)
	return _u
}

// SetNillableTransferPairID sets the "transfer_pair" edge to the Transaction entity by ID if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableTransferPairID(id *int) *TransactionUpdateOne {
	if id != nil {
		_u = _u.SetTransferPairID(*id)
	}
	return _u
}

// SetTransferPair sets the "transfer_pair" edge to the Transaction entity.
func (_u *TransactionUpdateOne) SetTransferPair(v *Transaction) *TransactionUpdateOne {
	return _u.SetTransferPairID(v.ID)
}

// SetTransferPairOfID sets the "transfer_pair_of" edge to the Transaction entity by ID.
func (_u *TransactionUpdateOne) SetTransferPairOfID(id int) *TransactionUpdateOne {
	_u.mutation.SetTransferPairOfID(id)
	return _u
}

// SetNillableTransferPairOfID sets the "transfer_pair_of" edge to the Transaction entity by ID if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableTransferPairOfID(id *int) *TransactionUpdateOne {
	if id != nil {
		_u = _u.SetTransferPairOfID(*id)
	}
	return _u
}

// SetTransferPairOf sets the "transfer_pair_of" edge to the Transaction entity.
func (_u *TransactionUpdateOne) SetTransferPairOf(v *Transaction) *TransactionUpdateOne {
	return _u.SetTransferPairOfID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdateOne) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *TransactionUpdateOne) ClearAccount() *TransactionUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *TransactionUpdateOne) ClearCategory() *TransactionUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// ClearRecurringInstance clears the "recurring_instance" edge to the RecurringInstance entity.
func (_u *TransactionUpdateOne) ClearRecurringInstance() *TransactionUpdateOne {
	_u.mutation.ClearRecurringInstance()
	return _u
}

// ClearTransferPair clears the "transfer_pair" edge to the Transaction entity.
func (_u *TransactionUpdateOne) ClearTransferPair() *TransactionUpdateOne {
	_u.mutation.ClearTransferPair()
	return _u
}

// ClearTransferPairOf clears the "transfer_pair_of" edge to the Transaction entity.
func (_u *TransactionUpdateOne) ClearTransferPairOf() *TransactionUpdateOne {
	_u.mutation.ClearTransferPairOf()
	return _u
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Transaction entity.
func (_u *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := transaction.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Transaction.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := transaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Transaction.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Classification(); ok {
		if err := transaction.ClassificationValidator(v); err != nil {
			return &ValidationError{Name: "classification", err: fmt.Errorf(`ent: validator failed for field "Transaction.classification": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Transaction.account"`)
	}
	return nil
}

func (_u *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(transaction.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PostedDate(); ok {
		_spec.SetField(transaction.FieldPostedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(transaction.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(transaction.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(transaction.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.Classification(); ok {
		_spec.SetField(transaction.FieldClassification, field.TypeEnum, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.CategoryTable,
			Columns: []string{transaction.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.CategoryTable,
			Columns: []string{transaction.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecurringInstanceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.RecurringInstanceTable,
			Columns: []string{transaction.RecurringInstanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringInstanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.RecurringInstanceTable,
			Columns: []string{transaction.RecurringInstanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransferPairCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   transaction.TransferPairTable,
			Columns: []string{transaction.TransferPairColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferPairIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   transaction.TransferPairTable,
			Columns: []string{transaction.TransferPairColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransferPairOfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.TransferPairOfTable,
			Columns: []string{transaction.TransferPairOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferPairOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transaction.TransferPairOfTable,
			Columns: []string{transaction.TransferPairOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Transaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
