// Code generated by ent, DO NOT EDIT.

package transaction

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the transaction type in the database.
	Label = "transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPostedDate holds the string denoting the posted_date field in the database.
	FieldPostedDate = "posted_date"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldClassification holds the string denoting the classification field in the database.
	FieldClassification = "classification"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeRecurringInstance holds the string denoting the recurring_instance edge name in mutations.
	EdgeRecurringInstance = "recurring_instance"
	// EdgeTransferPair holds the string denoting the transfer_pair edge name in mutations.
	EdgeTransferPair = "transfer_pair"
	// EdgeTransferPairOf holds the string denoting the transfer_pair_of edge name in mutations.
	EdgeTransferPairOf = "transfer_pair_of"
	// Table holds the table name of the transaction in the database.
	Table = "transactions"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "transactions"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_transactions"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "transactions"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_transactions"
	// RecurringInstanceTable is the table that holds the recurring_instance relation/edge.
	RecurringInstanceTable = "transactions"
	// RecurringInstanceInverseTable is the table name for the RecurringInstance entity.
	// It exists in this package in order to avoid circular dependency with the "recurringinstance" package.
	RecurringInstanceInverseTable = "recurring_instances"
	// RecurringInstanceColumn is the table column denoting the recurring_instance relation/edge.
	RecurringInstanceColumn = "recurring_instance_transaction"
	// TransferPairTable is the table that holds the transfer_pair relation/edge.
	TransferPairTable = "transactions"
	// TransferPairColumn is the table column denoting the transfer_pair relation/edge.
	TransferPairColumn = "transaction_transfer_pair"
	// TransferPairOfTable is the table that holds the transfer_pair_of relation/edge.
	TransferPairOfTable = "transactions"
	// TransferPairOfColumn is the table column denoting the transfer_pair_of relation/edge.
	TransferPairOfColumn = "transaction_transfer_pair"
)

// Columns holds all SQL columns for transaction fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldDescription,
	FieldPostedDate,
	FieldSource,
	FieldStatus,
	FieldExternalID,
	FieldClassification,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "transactions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_transactions",
	"category_transactions",
	"recurring_instance_transaction",
	"transaction_transfer_pair",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Source defines the type for the "source" enum field.
type Source string

// SourceManual is the default value of the Source enum.
const DefaultSource = SourceManual

// Source values.
const (
	SourceManual    Source = "manual"
	SourceSimplefin Source = "simplefin"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceManual, SourceSimplefin:
		return nil
	default:
		return fmt.Errorf("transaction: invalid enum value for source field: %q", s)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusProvisional is the default value of the Status enum.
const DefaultStatus = StatusProvisional

// Status values.
const (
	StatusProvisional Status = "provisional"
	StatusConfirmed   Status = "confirmed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusProvisional, StatusConfirmed:
		return nil
	default:
		return fmt.Errorf("transaction: invalid enum value for status field: %q", s)
	}
}

// Classification defines the type for the "classification" enum field.
type Classification string

// Classification values.
const (
	ClassificationDiscretionary        Classification = "discretionary"
	ClassificationRecurringFulfillment Classification = "recurring_fulfillment"
	ClassificationTransfer             Classification = "transfer"
	ClassificationIncome               Classification = "income"
)

func (c Classification) String() string {
	return string(c)
}

// ClassificationValidator is a validator for the "classification" field enum values. It is called by the builders before save.
func ClassificationValidator(c Classification) error {
	switch c {
	case ClassificationDiscretionary, ClassificationRecurringFulfillment, ClassificationTransfer, ClassificationIncome:
		return nil
	default:
		return fmt.Errorf("transaction: invalid enum value for classification field: %q", c)
	}
}

// OrderOption defines the ordering options for the Transaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPostedDate orders the results by the posted_date field.
func ByPostedDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostedDate, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByClassification orders the results by the classification field.
func ByClassification(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassification, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByRecurringInstanceField orders the results by recurring_instance field.
func ByRecurringInstanceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecurringInstanceStep(), sql.OrderByField(field, opts...))
	}
}

// ByTransferPairField orders the results by transfer_pair field.
func ByTransferPairField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransferPairStep(), sql.OrderByField(field, opts...))
	}
}

// ByTransferPairOfField orders the results by transfer_pair_of field.
func ByTransferPairOfField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransferPairOfStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
func newRecurringInstanceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecurringInstanceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, RecurringInstanceTable, RecurringInstanceColumn),
	)
}
func newTransferPairStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, TransferPairTable, TransferPairColumn),
	)
}
func newTransferPairOfStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TransferPairOfTable, TransferPairOfColumn),
	)
}
