// Code generated by ent, DO NOT EDIT.

package recurringinstance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/scott-woods/finance-app/apps/api/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldLTE(FieldID, id))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldDueDate, v))
}

// EstimatedAmount applies equality check predicate on the "estimated_amount" field. It's identical to EstimatedAmountEQ.
func EstimatedAmount(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldEstimatedAmount, v))
}

// ActualAmount applies equality check predicate on the "actual_amount" field. It's identical to ActualAmountEQ.
func ActualAmount(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldActualAmount, v))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldLTE(FieldDueDate, v))
}

// EstimatedAmountEQ applies the EQ predicate on the "estimated_amount" field.
func EstimatedAmountEQ(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldEstimatedAmount, v))
}

// EstimatedAmountNEQ applies the NEQ predicate on the "estimated_amount" field.
func EstimatedAmountNEQ(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNEQ(FieldEstimatedAmount, v))
}

// EstimatedAmountIn applies the In predicate on the "estimated_amount" field.
func EstimatedAmountIn(vs ...float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldIn(FieldEstimatedAmount, vs...))
}

// EstimatedAmountNotIn applies the NotIn predicate on the "estimated_amount" field.
func EstimatedAmountNotIn(vs ...float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNotIn(FieldEstimatedAmount, vs...))
}

// EstimatedAmountGT applies the GT predicate on the "estimated_amount" field.
func EstimatedAmountGT(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldGT(FieldEstimatedAmount, v))
}

// EstimatedAmountGTE applies the GTE predicate on the "estimated_amount" field.
func EstimatedAmountGTE(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldGTE(FieldEstimatedAmount, v))
}

// EstimatedAmountLT applies the LT predicate on the "estimated_amount" field.
func EstimatedAmountLT(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldLT(FieldEstimatedAmount, v))
}

// EstimatedAmountLTE applies the LTE predicate on the "estimated_amount" field.
func EstimatedAmountLTE(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldLTE(FieldEstimatedAmount, v))
}

// ActualAmountEQ applies the EQ predicate on the "actual_amount" field.
func ActualAmountEQ(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldActualAmount, v))
}

// ActualAmountNEQ applies the NEQ predicate on the "actual_amount" field.
func ActualAmountNEQ(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNEQ(FieldActualAmount, v))
}

// ActualAmountIn applies the In predicate on the "actual_amount" field.
func ActualAmountIn(vs ...float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldIn(FieldActualAmount, vs...))
}

// ActualAmountNotIn applies the NotIn predicate on the "actual_amount" field.
func ActualAmountNotIn(vs ...float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNotIn(FieldActualAmount, vs...))
}

// ActualAmountGT applies the GT predicate on the "actual_amount" field.
func ActualAmountGT(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldGT(FieldActualAmount, v))
}

// ActualAmountGTE applies the GTE predicate on the "actual_amount" field.
func ActualAmountGTE(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldGTE(FieldActualAmount, v))
}

// ActualAmountLT applies the LT predicate on the "actual_amount" field.
func ActualAmountLT(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldLT(FieldActualAmount, v))
}

// ActualAmountLTE applies the LTE predicate on the "actual_amount" field.
func ActualAmountLTE(v float64) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldLTE(FieldActualAmount, v))
}

// ActualAmountIsNil applies the IsNil predicate on the "actual_amount" field.
func ActualAmountIsNil() predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldIsNull(FieldActualAmount))
}

// ActualAmountNotNil applies the NotNil predicate on the "actual_amount" field.
func ActualAmountNotNil() predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNotNull(FieldActualAmount))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.FieldNotIn(FieldStatus, vs...))
}

// HasRecurringItem applies the HasEdge predicate on the "recurring_item" edge.
func HasRecurringItem() predicate.RecurringInstance {
	return predicate.RecurringInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RecurringItemTable, RecurringItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecurringItemWith applies the HasEdge predicate on the "recurring_item" edge with a given conditions (other predicates).
func HasRecurringItemWith(preds ...predicate.RecurringItem) predicate.RecurringInstance {
	return predicate.RecurringInstance(func(s *sql.Selector) {
		step := newRecurringItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransaction applies the HasEdge predicate on the "transaction" edge.
func HasTransaction() predicate.RecurringInstance {
	return predicate.RecurringInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, TransactionTable, TransactionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionWith applies the HasEdge predicate on the "transaction" edge with a given conditions (other predicates).
func HasTransactionWith(preds ...predicate.Transaction) predicate.RecurringInstance {
	return predicate.RecurringInstance(func(s *sql.Selector) {
		step := newTransactionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecurringInstance) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecurringInstance) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecurringInstance) predicate.RecurringInstance {
	return predicate.RecurringInstance(sql.NotPredicates(p))
}
